/*
 * This file is generated by jOOQ.
 */
package emented.jooq.main

import emented.jooq.main.tables.ActGeBytearray
import emented.jooq.main.tables.ActGeProperty
import emented.jooq.main.tables.ActGeSchemaLog
import emented.jooq.main.tables.ActHiActinst
import emented.jooq.main.tables.ActHiAttachment
import emented.jooq.main.tables.ActHiBatch
import emented.jooq.main.tables.ActHiCaseactinst
import emented.jooq.main.tables.ActHiCaseinst
import emented.jooq.main.tables.ActHiComment
import emented.jooq.main.tables.ActHiDecIn
import emented.jooq.main.tables.ActHiDecOut
import emented.jooq.main.tables.ActHiDecinst
import emented.jooq.main.tables.ActHiDetail
import emented.jooq.main.tables.ActHiExtTaskLog
import emented.jooq.main.tables.ActHiIdentitylink
import emented.jooq.main.tables.ActHiIncident
import emented.jooq.main.tables.ActHiJobLog
import emented.jooq.main.tables.ActHiOpLog
import emented.jooq.main.tables.ActHiProcinst
import emented.jooq.main.tables.ActHiTaskinst
import emented.jooq.main.tables.ActHiVarinst
import emented.jooq.main.tables.ActIdGroup
import emented.jooq.main.tables.ActIdInfo
import emented.jooq.main.tables.ActIdMembership
import emented.jooq.main.tables.ActIdTenant
import emented.jooq.main.tables.ActIdTenantMember
import emented.jooq.main.tables.ActIdUser
import emented.jooq.main.tables.ActReCamformdef
import emented.jooq.main.tables.ActReCaseDef
import emented.jooq.main.tables.ActReDecisionDef
import emented.jooq.main.tables.ActReDecisionReqDef
import emented.jooq.main.tables.ActReDeployment
import emented.jooq.main.tables.ActReProcdef
import emented.jooq.main.tables.ActRuAuthorization
import emented.jooq.main.tables.ActRuBatch
import emented.jooq.main.tables.ActRuCaseExecution
import emented.jooq.main.tables.ActRuCaseSentryPart
import emented.jooq.main.tables.ActRuEventSubscr
import emented.jooq.main.tables.ActRuExecution
import emented.jooq.main.tables.ActRuExtTask
import emented.jooq.main.tables.ActRuFilter
import emented.jooq.main.tables.ActRuIdentitylink
import emented.jooq.main.tables.ActRuIncident
import emented.jooq.main.tables.ActRuJob
import emented.jooq.main.tables.ActRuJobdef
import emented.jooq.main.tables.ActRuMeterLog
import emented.jooq.main.tables.ActRuTask
import emented.jooq.main.tables.ActRuTaskMeterLog
import emented.jooq.main.tables.ActRuVariable
import emented.jooq.main.tables.Category
import emented.jooq.main.tables.Comment
import emented.jooq.main.tables.Community
import emented.jooq.main.tables.CommunityEvent
import emented.jooq.main.tables.Films
import emented.jooq.main.tables.QrtzBlobTriggers
import emented.jooq.main.tables.QrtzCalendars
import emented.jooq.main.tables.QrtzCronTriggers
import emented.jooq.main.tables.QrtzFiredTriggers
import emented.jooq.main.tables.QrtzJobDetails
import emented.jooq.main.tables.QrtzLocks
import emented.jooq.main.tables.QrtzPausedTriggerGrps
import emented.jooq.main.tables.QrtzSchedulerState
import emented.jooq.main.tables.QrtzSimpleTriggers
import emented.jooq.main.tables.QrtzSimpropTriggers
import emented.jooq.main.tables.QrtzTriggers
import emented.jooq.main.tables.Reviews
import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.SchemaImpl

/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Public : SchemaImpl("public", DefaultCatalog.DEFAULT_CATALOG) {
    companion object {

        /**
         * The reference instance of <code>public</code>
         */
        val PUBLIC: Public = Public()
    }

    /**
     * The table <code>public.act_ge_bytearray</code>.
     */
    val ACT_GE_BYTEARRAY: ActGeBytearray get() = ActGeBytearray.ACT_GE_BYTEARRAY

    /**
     * The table <code>public.act_ge_property</code>.
     */
    val ACT_GE_PROPERTY: ActGeProperty get() = ActGeProperty.ACT_GE_PROPERTY

    /**
     * The table <code>public.act_ge_schema_log</code>.
     */
    val ACT_GE_SCHEMA_LOG: ActGeSchemaLog get() = ActGeSchemaLog.ACT_GE_SCHEMA_LOG

    /**
     * The table <code>public.act_hi_actinst</code>.
     */
    val ACT_HI_ACTINST: ActHiActinst get() = ActHiActinst.ACT_HI_ACTINST

    /**
     * The table <code>public.act_hi_attachment</code>.
     */
    val ACT_HI_ATTACHMENT: ActHiAttachment get() = ActHiAttachment.ACT_HI_ATTACHMENT

    /**
     * The table <code>public.act_hi_batch</code>.
     */
    val ACT_HI_BATCH: ActHiBatch get() = ActHiBatch.ACT_HI_BATCH

    /**
     * The table <code>public.act_hi_caseactinst</code>.
     */
    val ACT_HI_CASEACTINST: ActHiCaseactinst get() = ActHiCaseactinst.ACT_HI_CASEACTINST

    /**
     * The table <code>public.act_hi_caseinst</code>.
     */
    val ACT_HI_CASEINST: ActHiCaseinst get() = ActHiCaseinst.ACT_HI_CASEINST

    /**
     * The table <code>public.act_hi_comment</code>.
     */
    val ACT_HI_COMMENT: ActHiComment get() = ActHiComment.ACT_HI_COMMENT

    /**
     * The table <code>public.act_hi_dec_in</code>.
     */
    val ACT_HI_DEC_IN: ActHiDecIn get() = ActHiDecIn.ACT_HI_DEC_IN

    /**
     * The table <code>public.act_hi_dec_out</code>.
     */
    val ACT_HI_DEC_OUT: ActHiDecOut get() = ActHiDecOut.ACT_HI_DEC_OUT

    /**
     * The table <code>public.act_hi_decinst</code>.
     */
    val ACT_HI_DECINST: ActHiDecinst get() = ActHiDecinst.ACT_HI_DECINST

    /**
     * The table <code>public.act_hi_detail</code>.
     */
    val ACT_HI_DETAIL: ActHiDetail get() = ActHiDetail.ACT_HI_DETAIL

    /**
     * The table <code>public.act_hi_ext_task_log</code>.
     */
    val ACT_HI_EXT_TASK_LOG: ActHiExtTaskLog get() = ActHiExtTaskLog.ACT_HI_EXT_TASK_LOG

    /**
     * The table <code>public.act_hi_identitylink</code>.
     */
    val ACT_HI_IDENTITYLINK: ActHiIdentitylink get() = ActHiIdentitylink.ACT_HI_IDENTITYLINK

    /**
     * The table <code>public.act_hi_incident</code>.
     */
    val ACT_HI_INCIDENT: ActHiIncident get() = ActHiIncident.ACT_HI_INCIDENT

    /**
     * The table <code>public.act_hi_job_log</code>.
     */
    val ACT_HI_JOB_LOG: ActHiJobLog get() = ActHiJobLog.ACT_HI_JOB_LOG

    /**
     * The table <code>public.act_hi_op_log</code>.
     */
    val ACT_HI_OP_LOG: ActHiOpLog get() = ActHiOpLog.ACT_HI_OP_LOG

    /**
     * The table <code>public.act_hi_procinst</code>.
     */
    val ACT_HI_PROCINST: ActHiProcinst get() = ActHiProcinst.ACT_HI_PROCINST

    /**
     * The table <code>public.act_hi_taskinst</code>.
     */
    val ACT_HI_TASKINST: ActHiTaskinst get() = ActHiTaskinst.ACT_HI_TASKINST

    /**
     * The table <code>public.act_hi_varinst</code>.
     */
    val ACT_HI_VARINST: ActHiVarinst get() = ActHiVarinst.ACT_HI_VARINST

    /**
     * The table <code>public.act_id_group</code>.
     */
    val ACT_ID_GROUP: ActIdGroup get() = ActIdGroup.ACT_ID_GROUP

    /**
     * The table <code>public.act_id_info</code>.
     */
    val ACT_ID_INFO: ActIdInfo get() = ActIdInfo.ACT_ID_INFO

    /**
     * The table <code>public.act_id_membership</code>.
     */
    val ACT_ID_MEMBERSHIP: ActIdMembership get() = ActIdMembership.ACT_ID_MEMBERSHIP

    /**
     * The table <code>public.act_id_tenant</code>.
     */
    val ACT_ID_TENANT: ActIdTenant get() = ActIdTenant.ACT_ID_TENANT

    /**
     * The table <code>public.act_id_tenant_member</code>.
     */
    val ACT_ID_TENANT_MEMBER: ActIdTenantMember get() = ActIdTenantMember.ACT_ID_TENANT_MEMBER

    /**
     * The table <code>public.act_id_user</code>.
     */
    val ACT_ID_USER: ActIdUser get() = ActIdUser.ACT_ID_USER

    /**
     * The table <code>public.act_re_camformdef</code>.
     */
    val ACT_RE_CAMFORMDEF: ActReCamformdef get() = ActReCamformdef.ACT_RE_CAMFORMDEF

    /**
     * The table <code>public.act_re_case_def</code>.
     */
    val ACT_RE_CASE_DEF: ActReCaseDef get() = ActReCaseDef.ACT_RE_CASE_DEF

    /**
     * The table <code>public.act_re_decision_def</code>.
     */
    val ACT_RE_DECISION_DEF: ActReDecisionDef get() = ActReDecisionDef.ACT_RE_DECISION_DEF

    /**
     * The table <code>public.act_re_decision_req_def</code>.
     */
    val ACT_RE_DECISION_REQ_DEF: ActReDecisionReqDef get() = ActReDecisionReqDef.ACT_RE_DECISION_REQ_DEF

    /**
     * The table <code>public.act_re_deployment</code>.
     */
    val ACT_RE_DEPLOYMENT: ActReDeployment get() = ActReDeployment.ACT_RE_DEPLOYMENT

    /**
     * The table <code>public.act_re_procdef</code>.
     */
    val ACT_RE_PROCDEF: ActReProcdef get() = ActReProcdef.ACT_RE_PROCDEF

    /**
     * The table <code>public.act_ru_authorization</code>.
     */
    val ACT_RU_AUTHORIZATION: ActRuAuthorization get() = ActRuAuthorization.ACT_RU_AUTHORIZATION

    /**
     * The table <code>public.act_ru_batch</code>.
     */
    val ACT_RU_BATCH: ActRuBatch get() = ActRuBatch.ACT_RU_BATCH

    /**
     * The table <code>public.act_ru_case_execution</code>.
     */
    val ACT_RU_CASE_EXECUTION: ActRuCaseExecution get() = ActRuCaseExecution.ACT_RU_CASE_EXECUTION

    /**
     * The table <code>public.act_ru_case_sentry_part</code>.
     */
    val ACT_RU_CASE_SENTRY_PART: ActRuCaseSentryPart get() = ActRuCaseSentryPart.ACT_RU_CASE_SENTRY_PART

    /**
     * The table <code>public.act_ru_event_subscr</code>.
     */
    val ACT_RU_EVENT_SUBSCR: ActRuEventSubscr get() = ActRuEventSubscr.ACT_RU_EVENT_SUBSCR

    /**
     * The table <code>public.act_ru_execution</code>.
     */
    val ACT_RU_EXECUTION: ActRuExecution get() = ActRuExecution.ACT_RU_EXECUTION

    /**
     * The table <code>public.act_ru_ext_task</code>.
     */
    val ACT_RU_EXT_TASK: ActRuExtTask get() = ActRuExtTask.ACT_RU_EXT_TASK

    /**
     * The table <code>public.act_ru_filter</code>.
     */
    val ACT_RU_FILTER: ActRuFilter get() = ActRuFilter.ACT_RU_FILTER

    /**
     * The table <code>public.act_ru_identitylink</code>.
     */
    val ACT_RU_IDENTITYLINK: ActRuIdentitylink get() = ActRuIdentitylink.ACT_RU_IDENTITYLINK

    /**
     * The table <code>public.act_ru_incident</code>.
     */
    val ACT_RU_INCIDENT: ActRuIncident get() = ActRuIncident.ACT_RU_INCIDENT

    /**
     * The table <code>public.act_ru_job</code>.
     */
    val ACT_RU_JOB: ActRuJob get() = ActRuJob.ACT_RU_JOB

    /**
     * The table <code>public.act_ru_jobdef</code>.
     */
    val ACT_RU_JOBDEF: ActRuJobdef get() = ActRuJobdef.ACT_RU_JOBDEF

    /**
     * The table <code>public.act_ru_meter_log</code>.
     */
    val ACT_RU_METER_LOG: ActRuMeterLog get() = ActRuMeterLog.ACT_RU_METER_LOG

    /**
     * The table <code>public.act_ru_task</code>.
     */
    val ACT_RU_TASK: ActRuTask get() = ActRuTask.ACT_RU_TASK

    /**
     * The table <code>public.act_ru_task_meter_log</code>.
     */
    val ACT_RU_TASK_METER_LOG: ActRuTaskMeterLog get() = ActRuTaskMeterLog.ACT_RU_TASK_METER_LOG

    /**
     * The table <code>public.act_ru_variable</code>.
     */
    val ACT_RU_VARIABLE: ActRuVariable get() = ActRuVariable.ACT_RU_VARIABLE

    /**
     * The table <code>public.category</code>.
     */
    val CATEGORY: Category get() = Category.CATEGORY

    /**
     * The table <code>public.comment</code>.
     */
    val COMMENT: Comment get() = Comment.COMMENT

    /**
     * The table <code>public.community</code>.
     */
    val COMMUNITY: Community get() = Community.COMMUNITY

    /**
     * The table <code>public.community_event</code>.
     */
    val COMMUNITY_EVENT: CommunityEvent get() = CommunityEvent.COMMUNITY_EVENT

    /**
     * The table <code>public.films</code>.
     */
    val FILMS: Films get() = Films.FILMS

    /**
     * The table <code>public.qrtz_blob_triggers</code>.
     */
    val QRTZ_BLOB_TRIGGERS: QrtzBlobTriggers get() = QrtzBlobTriggers.QRTZ_BLOB_TRIGGERS

    /**
     * The table <code>public.qrtz_calendars</code>.
     */
    val QRTZ_CALENDARS: QrtzCalendars get() = QrtzCalendars.QRTZ_CALENDARS

    /**
     * The table <code>public.qrtz_cron_triggers</code>.
     */
    val QRTZ_CRON_TRIGGERS: QrtzCronTriggers get() = QrtzCronTriggers.QRTZ_CRON_TRIGGERS

    /**
     * The table <code>public.qrtz_fired_triggers</code>.
     */
    val QRTZ_FIRED_TRIGGERS: QrtzFiredTriggers get() = QrtzFiredTriggers.QRTZ_FIRED_TRIGGERS

    /**
     * The table <code>public.qrtz_job_details</code>.
     */
    val QRTZ_JOB_DETAILS: QrtzJobDetails get() = QrtzJobDetails.QRTZ_JOB_DETAILS

    /**
     * The table <code>public.qrtz_locks</code>.
     */
    val QRTZ_LOCKS: QrtzLocks get() = QrtzLocks.QRTZ_LOCKS

    /**
     * The table <code>public.qrtz_paused_trigger_grps</code>.
     */
    val QRTZ_PAUSED_TRIGGER_GRPS: QrtzPausedTriggerGrps get() = QrtzPausedTriggerGrps.QRTZ_PAUSED_TRIGGER_GRPS

    /**
     * The table <code>public.qrtz_scheduler_state</code>.
     */
    val QRTZ_SCHEDULER_STATE: QrtzSchedulerState get() = QrtzSchedulerState.QRTZ_SCHEDULER_STATE

    /**
     * The table <code>public.qrtz_simple_triggers</code>.
     */
    val QRTZ_SIMPLE_TRIGGERS: QrtzSimpleTriggers get() = QrtzSimpleTriggers.QRTZ_SIMPLE_TRIGGERS

    /**
     * The table <code>public.qrtz_simprop_triggers</code>.
     */
    val QRTZ_SIMPROP_TRIGGERS: QrtzSimpropTriggers get() = QrtzSimpropTriggers.QRTZ_SIMPROP_TRIGGERS

    /**
     * The table <code>public.qrtz_triggers</code>.
     */
    val QRTZ_TRIGGERS: QrtzTriggers get() = QrtzTriggers.QRTZ_TRIGGERS

    /**
     * The table <code>public.reviews</code>.
     */
    val REVIEWS: Reviews get() = Reviews.REVIEWS

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        ActGeBytearray.ACT_GE_BYTEARRAY,
        ActGeProperty.ACT_GE_PROPERTY,
        ActGeSchemaLog.ACT_GE_SCHEMA_LOG,
        ActHiActinst.ACT_HI_ACTINST,
        ActHiAttachment.ACT_HI_ATTACHMENT,
        ActHiBatch.ACT_HI_BATCH,
        ActHiCaseactinst.ACT_HI_CASEACTINST,
        ActHiCaseinst.ACT_HI_CASEINST,
        ActHiComment.ACT_HI_COMMENT,
        ActHiDecIn.ACT_HI_DEC_IN,
        ActHiDecOut.ACT_HI_DEC_OUT,
        ActHiDecinst.ACT_HI_DECINST,
        ActHiDetail.ACT_HI_DETAIL,
        ActHiExtTaskLog.ACT_HI_EXT_TASK_LOG,
        ActHiIdentitylink.ACT_HI_IDENTITYLINK,
        ActHiIncident.ACT_HI_INCIDENT,
        ActHiJobLog.ACT_HI_JOB_LOG,
        ActHiOpLog.ACT_HI_OP_LOG,
        ActHiProcinst.ACT_HI_PROCINST,
        ActHiTaskinst.ACT_HI_TASKINST,
        ActHiVarinst.ACT_HI_VARINST,
        ActIdGroup.ACT_ID_GROUP,
        ActIdInfo.ACT_ID_INFO,
        ActIdMembership.ACT_ID_MEMBERSHIP,
        ActIdTenant.ACT_ID_TENANT,
        ActIdTenantMember.ACT_ID_TENANT_MEMBER,
        ActIdUser.ACT_ID_USER,
        ActReCamformdef.ACT_RE_CAMFORMDEF,
        ActReCaseDef.ACT_RE_CASE_DEF,
        ActReDecisionDef.ACT_RE_DECISION_DEF,
        ActReDecisionReqDef.ACT_RE_DECISION_REQ_DEF,
        ActReDeployment.ACT_RE_DEPLOYMENT,
        ActReProcdef.ACT_RE_PROCDEF,
        ActRuAuthorization.ACT_RU_AUTHORIZATION,
        ActRuBatch.ACT_RU_BATCH,
        ActRuCaseExecution.ACT_RU_CASE_EXECUTION,
        ActRuCaseSentryPart.ACT_RU_CASE_SENTRY_PART,
        ActRuEventSubscr.ACT_RU_EVENT_SUBSCR,
        ActRuExecution.ACT_RU_EXECUTION,
        ActRuExtTask.ACT_RU_EXT_TASK,
        ActRuFilter.ACT_RU_FILTER,
        ActRuIdentitylink.ACT_RU_IDENTITYLINK,
        ActRuIncident.ACT_RU_INCIDENT,
        ActRuJob.ACT_RU_JOB,
        ActRuJobdef.ACT_RU_JOBDEF,
        ActRuMeterLog.ACT_RU_METER_LOG,
        ActRuTask.ACT_RU_TASK,
        ActRuTaskMeterLog.ACT_RU_TASK_METER_LOG,
        ActRuVariable.ACT_RU_VARIABLE,
        Category.CATEGORY,
        Comment.COMMENT,
        Community.COMMUNITY,
        CommunityEvent.COMMUNITY_EVENT,
        Films.FILMS,
        QrtzBlobTriggers.QRTZ_BLOB_TRIGGERS,
        QrtzCalendars.QRTZ_CALENDARS,
        QrtzCronTriggers.QRTZ_CRON_TRIGGERS,
        QrtzFiredTriggers.QRTZ_FIRED_TRIGGERS,
        QrtzJobDetails.QRTZ_JOB_DETAILS,
        QrtzLocks.QRTZ_LOCKS,
        QrtzPausedTriggerGrps.QRTZ_PAUSED_TRIGGER_GRPS,
        QrtzSchedulerState.QRTZ_SCHEDULER_STATE,
        QrtzSimpleTriggers.QRTZ_SIMPLE_TRIGGERS,
        QrtzSimpropTriggers.QRTZ_SIMPROP_TRIGGERS,
        QrtzTriggers.QRTZ_TRIGGERS,
        Reviews.REVIEWS
    )
}
