/*
 * This file is generated by jOOQ.
 */
package emented.jooq.main.tables.records

import emented.jooq.main.tables.ActGeBytearray
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl
import java.time.LocalDateTime

/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ActGeBytearrayRecord() : UpdatableRecordImpl<ActGeBytearrayRecord>(ActGeBytearray.ACT_GE_BYTEARRAY) {

    open var id_: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var rev_: Int?
        set(value): Unit = set(1, value)
        get(): Int? = get(1) as Int?

    open var name_: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var deploymentId_: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var bytes_: ByteArray?
        set(value): Unit = set(4, value)
        get(): ByteArray? = get(4) as ByteArray?

    open var generated_: Boolean?
        set(value): Unit = set(5, value)
        get(): Boolean? = get(5) as Boolean?

    open var tenantId_: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    open var type_: Int?
        set(value): Unit = set(7, value)
        get(): Int? = get(7) as Int?

    open var createTime_: LocalDateTime?
        set(value): Unit = set(8, value)
        get(): LocalDateTime? = get(8) as LocalDateTime?

    open var rootProcInstId_: String?
        set(value): Unit = set(9, value)
        get(): String? = get(9) as String?

    open var removalTime_: LocalDateTime?
        set(value): Unit = set(10, value)
        get(): LocalDateTime? = get(10) as LocalDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    /**
     * Create a detached, initialised ActGeBytearrayRecord
     */
    constructor(
        id_: String? = null,
        rev_: Int? = null,
        name_: String? = null,
        deploymentId_: String? = null,
        bytes_: ByteArray? = null,
        generated_: Boolean? = null,
        tenantId_: String? = null,
        type_: Int? = null,
        createTime_: LocalDateTime? = null,
        rootProcInstId_: String? = null,
        removalTime_: LocalDateTime? = null
    ) : this() {
        this.id_ = id_
        this.rev_ = rev_
        this.name_ = name_
        this.deploymentId_ = deploymentId_
        this.bytes_ = bytes_
        this.generated_ = generated_
        this.tenantId_ = tenantId_
        this.type_ = type_
        this.createTime_ = createTime_
        this.rootProcInstId_ = rootProcInstId_
        this.removalTime_ = removalTime_
        resetChangedOnNotNull()
    }
}
