/*
 * This file is generated by jOOQ.
 */
package emented.jooq.main.tables.records

import emented.jooq.main.tables.ActHiComment
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl
import java.time.LocalDateTime

/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ActHiCommentRecord() : UpdatableRecordImpl<ActHiCommentRecord>(ActHiComment.ACT_HI_COMMENT) {

    open var id_: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var type_: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var time_: LocalDateTime?
        set(value): Unit = set(2, value)
        get(): LocalDateTime? = get(2) as LocalDateTime?

    open var userId_: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var taskId_: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var rootProcInstId_: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    open var procInstId_: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    open var action_: String?
        set(value): Unit = set(7, value)
        get(): String? = get(7) as String?

    open var message_: String?
        set(value): Unit = set(8, value)
        get(): String? = get(8) as String?

    open var fullMsg_: ByteArray?
        set(value): Unit = set(9, value)
        get(): ByteArray? = get(9) as ByteArray?

    open var tenantId_: String?
        set(value): Unit = set(10, value)
        get(): String? = get(10) as String?

    open var removalTime_: LocalDateTime?
        set(value): Unit = set(11, value)
        get(): LocalDateTime? = get(11) as LocalDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    /**
     * Create a detached, initialised ActHiCommentRecord
     */
    constructor(
        id_: String? = null,
        type_: String? = null,
        time_: LocalDateTime? = null,
        userId_: String? = null,
        taskId_: String? = null,
        rootProcInstId_: String? = null,
        procInstId_: String? = null,
        action_: String? = null,
        message_: String? = null,
        fullMsg_: ByteArray? = null,
        tenantId_: String? = null,
        removalTime_: LocalDateTime? = null
    ) : this() {
        this.id_ = id_
        this.type_ = type_
        this.time_ = time_
        this.userId_ = userId_
        this.taskId_ = taskId_
        this.rootProcInstId_ = rootProcInstId_
        this.procInstId_ = procInstId_
        this.action_ = action_
        this.message_ = message_
        this.fullMsg_ = fullMsg_
        this.tenantId_ = tenantId_
        this.removalTime_ = removalTime_
        resetChangedOnNotNull()
    }
}
