/*
 * This file is generated by jOOQ.
 */
package emented.jooq.main.tables.records

import emented.jooq.main.tables.ActHiTaskinst
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl
import java.time.LocalDateTime

/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ActHiTaskinstRecord() : UpdatableRecordImpl<ActHiTaskinstRecord>(ActHiTaskinst.ACT_HI_TASKINST) {

    open var id_: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var taskDefKey_: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var procDefKey_: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var procDefId_: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var rootProcInstId_: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var procInstId_: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    open var executionId_: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    open var caseDefKey_: String?
        set(value): Unit = set(7, value)
        get(): String? = get(7) as String?

    open var caseDefId_: String?
        set(value): Unit = set(8, value)
        get(): String? = get(8) as String?

    open var caseInstId_: String?
        set(value): Unit = set(9, value)
        get(): String? = get(9) as String?

    open var caseExecutionId_: String?
        set(value): Unit = set(10, value)
        get(): String? = get(10) as String?

    open var actInstId_: String?
        set(value): Unit = set(11, value)
        get(): String? = get(11) as String?

    open var name_: String?
        set(value): Unit = set(12, value)
        get(): String? = get(12) as String?

    open var parentTaskId_: String?
        set(value): Unit = set(13, value)
        get(): String? = get(13) as String?

    open var description_: String?
        set(value): Unit = set(14, value)
        get(): String? = get(14) as String?

    open var owner_: String?
        set(value): Unit = set(15, value)
        get(): String? = get(15) as String?

    open var assignee_: String?
        set(value): Unit = set(16, value)
        get(): String? = get(16) as String?

    open var startTime_: LocalDateTime?
        set(value): Unit = set(17, value)
        get(): LocalDateTime? = get(17) as LocalDateTime?

    open var endTime_: LocalDateTime?
        set(value): Unit = set(18, value)
        get(): LocalDateTime? = get(18) as LocalDateTime?

    open var duration_: Long?
        set(value): Unit = set(19, value)
        get(): Long? = get(19) as Long?

    open var deleteReason_: String?
        set(value): Unit = set(20, value)
        get(): String? = get(20) as String?

    open var priority_: Int?
        set(value): Unit = set(21, value)
        get(): Int? = get(21) as Int?

    open var dueDate_: LocalDateTime?
        set(value): Unit = set(22, value)
        get(): LocalDateTime? = get(22) as LocalDateTime?

    open var followUpDate_: LocalDateTime?
        set(value): Unit = set(23, value)
        get(): LocalDateTime? = get(23) as LocalDateTime?

    open var tenantId_: String?
        set(value): Unit = set(24, value)
        get(): String? = get(24) as String?

    open var removalTime_: LocalDateTime?
        set(value): Unit = set(25, value)
        get(): LocalDateTime? = get(25) as LocalDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    /**
     * Create a detached, initialised ActHiTaskinstRecord
     */
    constructor(
        id_: String? = null,
        taskDefKey_: String? = null,
        procDefKey_: String? = null,
        procDefId_: String? = null,
        rootProcInstId_: String? = null,
        procInstId_: String? = null,
        executionId_: String? = null,
        caseDefKey_: String? = null,
        caseDefId_: String? = null,
        caseInstId_: String? = null,
        caseExecutionId_: String? = null,
        actInstId_: String? = null,
        name_: String? = null,
        parentTaskId_: String? = null,
        description_: String? = null,
        owner_: String? = null,
        assignee_: String? = null,
        startTime_: LocalDateTime? = null,
        endTime_: LocalDateTime? = null,
        duration_: Long? = null,
        deleteReason_: String? = null,
        priority_: Int? = null,
        dueDate_: LocalDateTime? = null,
        followUpDate_: LocalDateTime? = null,
        tenantId_: String? = null,
        removalTime_: LocalDateTime? = null
    ) : this() {
        this.id_ = id_
        this.taskDefKey_ = taskDefKey_
        this.procDefKey_ = procDefKey_
        this.procDefId_ = procDefId_
        this.rootProcInstId_ = rootProcInstId_
        this.procInstId_ = procInstId_
        this.executionId_ = executionId_
        this.caseDefKey_ = caseDefKey_
        this.caseDefId_ = caseDefId_
        this.caseInstId_ = caseInstId_
        this.caseExecutionId_ = caseExecutionId_
        this.actInstId_ = actInstId_
        this.name_ = name_
        this.parentTaskId_ = parentTaskId_
        this.description_ = description_
        this.owner_ = owner_
        this.assignee_ = assignee_
        this.startTime_ = startTime_
        this.endTime_ = endTime_
        this.duration_ = duration_
        this.deleteReason_ = deleteReason_
        this.priority_ = priority_
        this.dueDate_ = dueDate_
        this.followUpDate_ = followUpDate_
        this.tenantId_ = tenantId_
        this.removalTime_ = removalTime_
        resetChangedOnNotNull()
    }
}
