/*
 * This file is generated by jOOQ.
 */
package emented.jooq.main.tables.records

import emented.jooq.main.tables.ActIdMembership

import org.jooq.Record2
import org.jooq.impl.UpdatableRecordImpl

/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ActIdMembershipRecord() : UpdatableRecordImpl<ActIdMembershipRecord>(ActIdMembership.ACT_ID_MEMBERSHIP) {

    open var userId_: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var groupId_: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record2<String?, String?> = super.key() as Record2<String?, String?>

    /**
     * Create a detached, initialised ActIdMembershipRecord
     */
    constructor(userId_: String? = null, groupId_: String? = null) : this() {
        this.userId_ = userId_
        this.groupId_ = groupId_
        resetChangedOnNotNull()
    }
}
