/*
 * This file is generated by jOOQ.
 */
package emented.jooq.main.tables.records

import emented.jooq.main.tables.ActRuIdentitylink

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl

/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ActRuIdentitylinkRecord() :
    UpdatableRecordImpl<ActRuIdentitylinkRecord>(ActRuIdentitylink.ACT_RU_IDENTITYLINK) {

    open var id_: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var rev_: Int?
        set(value): Unit = set(1, value)
        get(): Int? = get(1) as Int?

    open var groupId_: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var type_: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var userId_: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var taskId_: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    open var procDefId_: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    open var tenantId_: String?
        set(value): Unit = set(7, value)
        get(): String? = get(7) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    /**
     * Create a detached, initialised ActRuIdentitylinkRecord
     */
    constructor(
        id_: String? = null,
        rev_: Int? = null,
        groupId_: String? = null,
        type_: String? = null,
        userId_: String? = null,
        taskId_: String? = null,
        procDefId_: String? = null,
        tenantId_: String? = null
    ) : this() {
        this.id_ = id_
        this.rev_ = rev_
        this.groupId_ = groupId_
        this.type_ = type_
        this.userId_ = userId_
        this.taskId_ = taskId_
        this.procDefId_ = procDefId_
        this.tenantId_ = tenantId_
        resetChangedOnNotNull()
    }
}
