/*
 * This file is generated by jOOQ.
 */
package emented.jooq.main.tables.records

import emented.jooq.main.tables.ActRuCaseSentryPart

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl

/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ActRuCaseSentryPartRecord() :
    UpdatableRecordImpl<ActRuCaseSentryPartRecord>(ActRuCaseSentryPart.ACT_RU_CASE_SENTRY_PART) {

    open var id_: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var rev_: Int?
        set(value): Unit = set(1, value)
        get(): Int? = get(1) as Int?

    open var caseInstId_: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var caseExecId_: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var sentryId_: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var type_: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    open var sourceCaseExecId_: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    open var standardEvent_: String?
        set(value): Unit = set(7, value)
        get(): String? = get(7) as String?

    open var source_: String?
        set(value): Unit = set(8, value)
        get(): String? = get(8) as String?

    open var variableEvent_: String?
        set(value): Unit = set(9, value)
        get(): String? = get(9) as String?

    open var variableName_: String?
        set(value): Unit = set(10, value)
        get(): String? = get(10) as String?

    open var satisfied_: Boolean?
        set(value): Unit = set(11, value)
        get(): Boolean? = get(11) as Boolean?

    open var tenantId_: String?
        set(value): Unit = set(12, value)
        get(): String? = get(12) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    /**
     * Create a detached, initialised ActRuCaseSentryPartRecord
     */
    constructor(
        id_: String? = null,
        rev_: Int? = null,
        caseInstId_: String? = null,
        caseExecId_: String? = null,
        sentryId_: String? = null,
        type_: String? = null,
        sourceCaseExecId_: String? = null,
        standardEvent_: String? = null,
        source_: String? = null,
        variableEvent_: String? = null,
        variableName_: String? = null,
        satisfied_: Boolean? = null,
        tenantId_: String? = null
    ) : this() {
        this.id_ = id_
        this.rev_ = rev_
        this.caseInstId_ = caseInstId_
        this.caseExecId_ = caseExecId_
        this.sentryId_ = sentryId_
        this.type_ = type_
        this.sourceCaseExecId_ = sourceCaseExecId_
        this.standardEvent_ = standardEvent_
        this.source_ = source_
        this.variableEvent_ = variableEvent_
        this.variableName_ = variableName_
        this.satisfied_ = satisfied_
        this.tenantId_ = tenantId_
        resetChangedOnNotNull()
    }
}
