/*
 * This file is generated by jOOQ.
 */
package emented.jooq.main.tables.records

import emented.jooq.main.tables.ActRuExecution

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl

/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ActRuExecutionRecord() : UpdatableRecordImpl<ActRuExecutionRecord>(ActRuExecution.ACT_RU_EXECUTION) {

    open var id_: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var rev_: Int?
        set(value): Unit = set(1, value)
        get(): Int? = get(1) as Int?

    open var rootProcInstId_: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var procInstId_: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var businessKey_: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var parentId_: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    open var procDefId_: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    open var superExec_: String?
        set(value): Unit = set(7, value)
        get(): String? = get(7) as String?

    open var superCaseExec_: String?
        set(value): Unit = set(8, value)
        get(): String? = get(8) as String?

    open var caseInstId_: String?
        set(value): Unit = set(9, value)
        get(): String? = get(9) as String?

    open var actId_: String?
        set(value): Unit = set(10, value)
        get(): String? = get(10) as String?

    open var actInstId_: String?
        set(value): Unit = set(11, value)
        get(): String? = get(11) as String?

    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsActive_")
    open var isActive_: Boolean?
        set(value): Unit = set(12, value)
        get(): Boolean? = get(12) as Boolean?

    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsConcurrent_")
    open var isConcurrent_: Boolean?
        set(value): Unit = set(13, value)
        get(): Boolean? = get(13) as Boolean?

    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsScope_")
    open var isScope_: Boolean?
        set(value): Unit = set(14, value)
        get(): Boolean? = get(14) as Boolean?

    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsEventScope_")
    open var isEventScope_: Boolean?
        set(value): Unit = set(15, value)
        get(): Boolean? = get(15) as Boolean?

    open var suspensionState_: Int?
        set(value): Unit = set(16, value)
        get(): Int? = get(16) as Int?

    open var cachedEntState_: Int?
        set(value): Unit = set(17, value)
        get(): Int? = get(17) as Int?

    open var sequenceCounter_: Long?
        set(value): Unit = set(18, value)
        get(): Long? = get(18) as Long?

    open var tenantId_: String?
        set(value): Unit = set(19, value)
        get(): String? = get(19) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    /**
     * Create a detached, initialised ActRuExecutionRecord
     */
    constructor(
        id_: String? = null,
        rev_: Int? = null,
        rootProcInstId_: String? = null,
        procInstId_: String? = null,
        businessKey_: String? = null,
        parentId_: String? = null,
        procDefId_: String? = null,
        superExec_: String? = null,
        superCaseExec_: String? = null,
        caseInstId_: String? = null,
        actId_: String? = null,
        actInstId_: String? = null,
        isActive_: Boolean? = null,
        isConcurrent_: Boolean? = null,
        isScope_: Boolean? = null,
        isEventScope_: Boolean? = null,
        suspensionState_: Int? = null,
        cachedEntState_: Int? = null,
        sequenceCounter_: Long? = null,
        tenantId_: String? = null
    ) : this() {
        this.id_ = id_
        this.rev_ = rev_
        this.rootProcInstId_ = rootProcInstId_
        this.procInstId_ = procInstId_
        this.businessKey_ = businessKey_
        this.parentId_ = parentId_
        this.procDefId_ = procDefId_
        this.superExec_ = superExec_
        this.superCaseExec_ = superCaseExec_
        this.caseInstId_ = caseInstId_
        this.actId_ = actId_
        this.actInstId_ = actInstId_
        this.isActive_ = isActive_
        this.isConcurrent_ = isConcurrent_
        this.isScope_ = isScope_
        this.isEventScope_ = isEventScope_
        this.suspensionState_ = suspensionState_
        this.cachedEntState_ = cachedEntState_
        this.sequenceCounter_ = sequenceCounter_
        this.tenantId_ = tenantId_
        resetChangedOnNotNull()
    }
}
