/*
 * This file is generated by jOOQ.
 */
package emented.jooq.main.tables.records

import emented.jooq.main.tables.ActRuJobdef

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl

/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ActRuJobdefRecord() : UpdatableRecordImpl<ActRuJobdefRecord>(ActRuJobdef.ACT_RU_JOBDEF) {

    open var id_: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var rev_: Int?
        set(value): Unit = set(1, value)
        get(): Int? = get(1) as Int?

    open var procDefId_: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var procDefKey_: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var actId_: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var jobType_: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    open var jobConfiguration_: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    open var suspensionState_: Int?
        set(value): Unit = set(7, value)
        get(): Int? = get(7) as Int?

    open var jobPriority_: Long?
        set(value): Unit = set(8, value)
        get(): Long? = get(8) as Long?

    open var tenantId_: String?
        set(value): Unit = set(9, value)
        get(): String? = get(9) as String?

    open var deploymentId_: String?
        set(value): Unit = set(10, value)
        get(): String? = get(10) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    /**
     * Create a detached, initialised ActRuJobdefRecord
     */
    constructor(
        id_: String? = null,
        rev_: Int? = null,
        procDefId_: String? = null,
        procDefKey_: String? = null,
        actId_: String? = null,
        jobType_: String? = null,
        jobConfiguration_: String? = null,
        suspensionState_: Int? = null,
        jobPriority_: Long? = null,
        tenantId_: String? = null,
        deploymentId_: String? = null
    ) : this() {
        this.id_ = id_
        this.rev_ = rev_
        this.procDefId_ = procDefId_
        this.procDefKey_ = procDefKey_
        this.actId_ = actId_
        this.jobType_ = jobType_
        this.jobConfiguration_ = jobConfiguration_
        this.suspensionState_ = suspensionState_
        this.jobPriority_ = jobPriority_
        this.tenantId_ = tenantId_
        this.deploymentId_ = deploymentId_
        resetChangedOnNotNull()
    }
}
