/*
 * This file is generated by jOOQ.
 */
package emented.jooq.main.tables.records

import emented.jooq.main.tables.ActReDeployment
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl
import java.time.LocalDateTime

/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ActReDeploymentRecord() : UpdatableRecordImpl<ActReDeploymentRecord>(ActReDeployment.ACT_RE_DEPLOYMENT) {

    open var id_: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var name_: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var deployTime_: LocalDateTime?
        set(value): Unit = set(2, value)
        get(): LocalDateTime? = get(2) as LocalDateTime?

    open var source_: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var tenantId_: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    /**
     * Create a detached, initialised ActReDeploymentRecord
     */
    constructor(
        id_: String? = null,
        name_: String? = null,
        deployTime_: LocalDateTime? = null,
        source_: String? = null,
        tenantId_: String? = null
    ) : this() {
        this.id_ = id_
        this.name_ = name_
        this.deployTime_ = deployTime_
        this.source_ = source_
        this.tenantId_ = tenantId_
        resetChangedOnNotNull()
    }
}
