/*
 * This file is generated by jOOQ.
 */
package emented.jooq.main.tables.records

import emented.jooq.main.tables.ActRuMeterLog
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl
import java.time.LocalDateTime

/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ActRuMeterLogRecord() : UpdatableRecordImpl<ActRuMeterLogRecord>(ActRuMeterLog.ACT_RU_METER_LOG) {

    open var id_: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var name_: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var reporter_: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var value_: Long?
        set(value): Unit = set(3, value)
        get(): Long? = get(3) as Long?

    open var timestamp_: LocalDateTime?
        set(value): Unit = set(4, value)
        get(): LocalDateTime? = get(4) as LocalDateTime?

    open var milliseconds_: Long?
        set(value): Unit = set(5, value)
        get(): Long? = get(5) as Long?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    /**
     * Create a detached, initialised ActRuMeterLogRecord
     */
    constructor(
        id_: String? = null,
        name_: String? = null,
        reporter_: String? = null,
        value_: Long? = null,
        timestamp_: LocalDateTime? = null,
        milliseconds_: Long? = null
    ) : this() {
        this.id_ = id_
        this.name_ = name_
        this.reporter_ = reporter_
        this.value_ = value_
        this.timestamp_ = timestamp_
        this.milliseconds_ = milliseconds_
        resetChangedOnNotNull()
    }
}
