/*
 * This file is generated by jOOQ.
 */
package emented.jooq.main.tables.records

import emented.jooq.main.tables.ActRuJob
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl
import java.time.LocalDateTime

/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ActRuJobRecord() : UpdatableRecordImpl<ActRuJobRecord>(ActRuJob.ACT_RU_JOB) {

    open var id_: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var rev_: Int?
        set(value): Unit = set(1, value)
        get(): Int? = get(1) as Int?

    open var type_: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var lockExpTime_: LocalDateTime?
        set(value): Unit = set(3, value)
        get(): LocalDateTime? = get(3) as LocalDateTime?

    open var lockOwner_: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var exclusive_: Boolean?
        set(value): Unit = set(5, value)
        get(): Boolean? = get(5) as Boolean?

    open var executionId_: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    open var rootProcInstId_: String?
        set(value): Unit = set(7, value)
        get(): String? = get(7) as String?

    open var processInstanceId_: String?
        set(value): Unit = set(8, value)
        get(): String? = get(8) as String?

    open var processDefId_: String?
        set(value): Unit = set(9, value)
        get(): String? = get(9) as String?

    open var processDefKey_: String?
        set(value): Unit = set(10, value)
        get(): String? = get(10) as String?

    open var retries_: Int?
        set(value): Unit = set(11, value)
        get(): Int? = get(11) as Int?

    open var exceptionStackId_: String?
        set(value): Unit = set(12, value)
        get(): String? = get(12) as String?

    open var exceptionMsg_: String?
        set(value): Unit = set(13, value)
        get(): String? = get(13) as String?

    open var failedActId_: String?
        set(value): Unit = set(14, value)
        get(): String? = get(14) as String?

    open var duedate_: LocalDateTime?
        set(value): Unit = set(15, value)
        get(): LocalDateTime? = get(15) as LocalDateTime?

    open var repeat_: String?
        set(value): Unit = set(16, value)
        get(): String? = get(16) as String?

    open var repeatOffset_: Long?
        set(value): Unit = set(17, value)
        get(): Long? = get(17) as Long?

    open var handlerType_: String?
        set(value): Unit = set(18, value)
        get(): String? = get(18) as String?

    open var handlerCfg_: String?
        set(value): Unit = set(19, value)
        get(): String? = get(19) as String?

    open var deploymentId_: String?
        set(value): Unit = set(20, value)
        get(): String? = get(20) as String?

    open var suspensionState_: Int?
        set(value): Unit = set(21, value)
        get(): Int? = get(21) as Int?

    open var jobDefId_: String?
        set(value): Unit = set(22, value)
        get(): String? = get(22) as String?

    open var priority_: Long?
        set(value): Unit = set(23, value)
        get(): Long? = get(23) as Long?

    open var sequenceCounter_: Long?
        set(value): Unit = set(24, value)
        get(): Long? = get(24) as Long?

    open var tenantId_: String?
        set(value): Unit = set(25, value)
        get(): String? = get(25) as String?

    open var createTime_: LocalDateTime?
        set(value): Unit = set(26, value)
        get(): LocalDateTime? = get(26) as LocalDateTime?

    open var lastFailureLogId_: String?
        set(value): Unit = set(27, value)
        get(): String? = get(27) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    /**
     * Create a detached, initialised ActRuJobRecord
     */
    constructor(
        id_: String? = null,
        rev_: Int? = null,
        type_: String? = null,
        lockExpTime_: LocalDateTime? = null,
        lockOwner_: String? = null,
        exclusive_: Boolean? = null,
        executionId_: String? = null,
        rootProcInstId_: String? = null,
        processInstanceId_: String? = null,
        processDefId_: String? = null,
        processDefKey_: String? = null,
        retries_: Int? = null,
        exceptionStackId_: String? = null,
        exceptionMsg_: String? = null,
        failedActId_: String? = null,
        duedate_: LocalDateTime? = null,
        repeat_: String? = null,
        repeatOffset_: Long? = null,
        handlerType_: String? = null,
        handlerCfg_: String? = null,
        deploymentId_: String? = null,
        suspensionState_: Int? = null,
        jobDefId_: String? = null,
        priority_: Long? = null,
        sequenceCounter_: Long? = null,
        tenantId_: String? = null,
        createTime_: LocalDateTime? = null,
        lastFailureLogId_: String? = null
    ) : this() {
        this.id_ = id_
        this.rev_ = rev_
        this.type_ = type_
        this.lockExpTime_ = lockExpTime_
        this.lockOwner_ = lockOwner_
        this.exclusive_ = exclusive_
        this.executionId_ = executionId_
        this.rootProcInstId_ = rootProcInstId_
        this.processInstanceId_ = processInstanceId_
        this.processDefId_ = processDefId_
        this.processDefKey_ = processDefKey_
        this.retries_ = retries_
        this.exceptionStackId_ = exceptionStackId_
        this.exceptionMsg_ = exceptionMsg_
        this.failedActId_ = failedActId_
        this.duedate_ = duedate_
        this.repeat_ = repeat_
        this.repeatOffset_ = repeatOffset_
        this.handlerType_ = handlerType_
        this.handlerCfg_ = handlerCfg_
        this.deploymentId_ = deploymentId_
        this.suspensionState_ = suspensionState_
        this.jobDefId_ = jobDefId_
        this.priority_ = priority_
        this.sequenceCounter_ = sequenceCounter_
        this.tenantId_ = tenantId_
        this.createTime_ = createTime_
        this.lastFailureLogId_ = lastFailureLogId_
        resetChangedOnNotNull()
    }
}
