/*
 * This file is generated by jOOQ.
 */
package emented.jooq.main.tables.records

import emented.jooq.main.tables.CommunityEvent
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl
import java.time.OffsetDateTime

/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class CommunityEventRecord() : UpdatableRecordImpl<CommunityEventRecord>(CommunityEvent.COMMUNITY_EVENT) {

    open var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var communityId: Long?
        set(value): Unit = set(1, value)
        get(): Long? = get(1) as Long?

    open var name: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var address: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var language: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var description: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsForChildren")
    open var isForChildren: Boolean?
        set(value): Unit = set(6, value)
        get(): Boolean? = get(6) as Boolean?

    open var categoryId: Long?
        set(value): Unit = set(7, value)
        get(): Long? = get(7) as Long?

    open var userId: Long?
        set(value): Unit = set(8, value)
        get(): Long? = get(8) as Long?

    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsBlocked")
    open var isBlocked: Boolean?
        set(value): Unit = set(9, value)
        get(): Boolean? = get(9) as Boolean?

    open var interestRate: Long?
        set(value): Unit = set(10, value)
        get(): Long? = get(10) as Long?

    open var creationTs: OffsetDateTime?
        set(value): Unit = set(11, value)
        get(): OffsetDateTime? = get(11) as OffsetDateTime?

    open var eventType: String?
        set(value): Unit = set(12, value)
        get(): String? = get(12) as String?

    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsSent")
    open var isSent: Boolean?
        set(value): Unit = set(13, value)
        get(): Boolean? = get(13) as Boolean?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    /**
     * Create a detached, initialised CommunityEventRecord
     */
    constructor(
        id: Long? = null,
        communityId: Long? = null,
        name: String? = null,
        address: String? = null,
        language: String? = null,
        description: String? = null,
        isForChildren: Boolean? = null,
        categoryId: Long? = null,
        userId: Long? = null,
        isBlocked: Boolean? = null,
        interestRate: Long? = null,
        creationTs: OffsetDateTime? = null,
        eventType: String? = null,
        isSent: Boolean? = null
    ) : this() {
        this.id = id
        this.communityId = communityId
        this.name = name
        this.address = address
        this.language = language
        this.description = description
        this.isForChildren = isForChildren
        this.categoryId = categoryId
        this.userId = userId
        this.isBlocked = isBlocked
        this.interestRate = interestRate
        this.creationTs = creationTs
        this.eventType = eventType
        this.isSent = isSent
        resetChangedOnNotNull()
    }
}
