/*
 * This file is generated by jOOQ.
 */
package emented.jooq.main.tables.records


import emented.jooq.main.tables.QrtzPausedTriggerGrps

import org.jooq.Record2
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class QrtzPausedTriggerGrpsRecord() : UpdatableRecordImpl<QrtzPausedTriggerGrpsRecord>(QrtzPausedTriggerGrps.QRTZ_PAUSED_TRIGGER_GRPS) {

    open var schedName: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var triggerGroup: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record2<String?, String?> = super.key() as Record2<String?, String?>

    /**
     * Create a detached, initialised QrtzPausedTriggerGrpsRecord
     */
    constructor(schedName: String? = null, triggerGroup: String? = null): this() {
        this.schedName = schedName
        this.triggerGroup = triggerGroup
        resetChangedOnNotNull()
    }
}
