/*
 * This file is generated by jOOQ.
 */
package emented.jooq.main.tables.records


import emented.jooq.main.tables.QrtzJobDetails

import org.jooq.Record3
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class QrtzJobDetailsRecord() : UpdatableRecordImpl<QrtzJobDetailsRecord>(QrtzJobDetails.QRTZ_JOB_DETAILS) {

    open var schedName: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var jobName: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var jobGroup: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var description: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var jobClassName: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsDurable")
    open var isDurable: Boolean?
        set(value): Unit = set(5, value)
        get(): Boolean? = get(5) as Boolean?

    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsNonconcurrent")
    open var isNonconcurrent: Boolean?
        set(value): Unit = set(6, value)
        get(): Boolean? = get(6) as Boolean?

    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsUpdateData")
    open var isUpdateData: Boolean?
        set(value): Unit = set(7, value)
        get(): Boolean? = get(7) as Boolean?

    open var requestsRecovery: Boolean?
        set(value): Unit = set(8, value)
        get(): Boolean? = get(8) as Boolean?

    open var jobData: ByteArray?
        set(value): Unit = set(9, value)
        get(): ByteArray? = get(9) as ByteArray?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record3<String?, String?, String?> = super.key() as Record3<String?, String?, String?>

    /**
     * Create a detached, initialised QrtzJobDetailsRecord
     */
    constructor(schedName: String? = null, jobName: String? = null, jobGroup: String? = null, description: String? = null, jobClassName: String? = null, isDurable: Boolean? = null, isNonconcurrent: Boolean? = null, isUpdateData: Boolean? = null, requestsRecovery: Boolean? = null, jobData: ByteArray? = null): this() {
        this.schedName = schedName
        this.jobName = jobName
        this.jobGroup = jobGroup
        this.description = description
        this.jobClassName = jobClassName
        this.isDurable = isDurable
        this.isNonconcurrent = isNonconcurrent
        this.isUpdateData = isUpdateData
        this.requestsRecovery = requestsRecovery
        this.jobData = jobData
        resetChangedOnNotNull()
    }
}
