/*
 * This file is generated by jOOQ.
 */
package emented.jooq.main.tables.records


import emented.jooq.main.tables.QrtzCalendars

import org.jooq.Record2
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class QrtzCalendarsRecord() : UpdatableRecordImpl<QrtzCalendarsRecord>(QrtzCalendars.QRTZ_CALENDARS) {

    open var schedName: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var calendarName: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var calendar: ByteArray?
        set(value): Unit = set(2, value)
        get(): ByteArray? = get(2) as ByteArray?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record2<String?, String?> = super.key() as Record2<String?, String?>

    /**
     * Create a detached, initialised QrtzCalendarsRecord
     */
    constructor(schedName: String? = null, calendarName: String? = null, calendar: ByteArray? = null): this() {
        this.schedName = schedName
        this.calendarName = calendarName
        this.calendar = calendar
        resetChangedOnNotNull()
    }
}
