/*
 * This file is generated by jOOQ.
 */
package emented.jooq.archive.tables.records


import emented.jooq.archive.tables.CommunityArchive

import java.time.OffsetDateTime

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class CommunityArchiveRecord() : UpdatableRecordImpl<CommunityArchiveRecord>(CommunityArchive.COMMUNITY_ARCHIVE) {

    open var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var name: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var address: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var language: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var description: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsForChildren")
    open var isForChildren: Boolean?
        set(value): Unit = set(5, value)
        get(): Boolean? = get(5) as Boolean?

    open var categoryName: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    open var userId: Long?
        set(value): Unit = set(7, value)
        get(): Long? = get(7) as Long?

    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsBlocked")
    open var isBlocked: Boolean?
        set(value): Unit = set(8, value)
        get(): Boolean? = get(8) as Boolean?

    open var interestRate: Long?
        set(value): Unit = set(9, value)
        get(): Long? = get(9) as Long?

    open var moderationResult: String?
        set(value): Unit = set(10, value)
        get(): String? = get(10) as String?

    open var moderationMessage: String?
        set(value): Unit = set(11, value)
        get(): String? = get(11) as String?

    open var creationTs: OffsetDateTime?
        set(value): Unit = set(12, value)
        get(): OffsetDateTime? = get(12) as OffsetDateTime?

    open var updateTs: OffsetDateTime?
        set(value): Unit = set(13, value)
        get(): OffsetDateTime? = get(13) as OffsetDateTime?

    open var archivationTs: OffsetDateTime?
        set(value): Unit = set(14, value)
        get(): OffsetDateTime? = get(14) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    /**
     * Create a detached, initialised CommunityArchiveRecord
     */
    constructor(id: Long? = null, name: String? = null, address: String? = null, language: String? = null, description: String? = null, isForChildren: Boolean? = null, categoryName: String? = null, userId: Long? = null, isBlocked: Boolean? = null, interestRate: Long? = null, moderationResult: String? = null, moderationMessage: String? = null, creationTs: OffsetDateTime? = null, updateTs: OffsetDateTime? = null, archivationTs: OffsetDateTime? = null): this() {
        this.id = id
        this.name = name
        this.address = address
        this.language = language
        this.description = description
        this.isForChildren = isForChildren
        this.categoryName = categoryName
        this.userId = userId
        this.isBlocked = isBlocked
        this.interestRate = interestRate
        this.moderationResult = moderationResult
        this.moderationMessage = moderationMessage
        this.creationTs = creationTs
        this.updateTs = updateTs
        this.archivationTs = archivationTs
        resetChangedOnNotNull()
    }
}
