/*
 * This file is generated by jOOQ.
 */
package emented.jooq.main.tables

import emented.jooq.main.Public
import emented.jooq.main.keys.ACT_GE_PROPERTY_PKEY
import emented.jooq.main.tables.records.ActGePropertyRecord
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl

/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ActGeProperty(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, ActGePropertyRecord>?,
    parentPath: InverseForeignKey<out Record, ActGePropertyRecord>?,
    aliased: Table<ActGePropertyRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
) : TableImpl<ActGePropertyRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.act_ge_property</code>
         */
        val ACT_GE_PROPERTY: ActGeProperty = ActGeProperty()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<ActGePropertyRecord> = ActGePropertyRecord::class.java

    /**
     * The column <code>public.act_ge_property.name_</code>.
     */
    val NAME_: TableField<ActGePropertyRecord, String?> =
        createField(DSL.name("name_"), SQLDataType.VARCHAR(64).nullable(false), this, "")

    /**
     * The column <code>public.act_ge_property.value_</code>.
     */
    val VALUE_: TableField<ActGePropertyRecord, String?> =
        createField(DSL.name("value_"), SQLDataType.VARCHAR(300), this, "")

    /**
     * The column <code>public.act_ge_property.rev_</code>.
     */
    val REV_: TableField<ActGePropertyRecord, Int?> = createField(DSL.name("rev_"), SQLDataType.INTEGER, this, "")

    private constructor(alias: Name, aliased: Table<ActGePropertyRecord>?) : this(
        alias,
        null,
        null,
        null,
        aliased,
        null,
        null
    )

    private constructor(alias: Name, aliased: Table<ActGePropertyRecord>?, parameters: Array<Field<*>?>?) : this(
        alias,
        null,
        null,
        null,
        aliased,
        parameters,
        null
    )

    private constructor(alias: Name, aliased: Table<ActGePropertyRecord>?, where: Condition?) : this(
        alias,
        null,
        null,
        null,
        aliased,
        null,
        where
    )

    /**
     * Create an aliased <code>public.act_ge_property</code> table reference
     */
    constructor(alias: String) : this(DSL.name(alias))

    /**
     * Create an aliased <code>public.act_ge_property</code> table reference
     */
    constructor(alias: Name) : this(alias, null)

    /**
     * Create a <code>public.act_ge_property</code> table reference
     */
    constructor() : this(DSL.name("act_ge_property"), null)

    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<ActGePropertyRecord> = ACT_GE_PROPERTY_PKEY
    override fun `as`(alias: String): ActGeProperty = ActGeProperty(DSL.name(alias), this)
    override fun `as`(alias: Name): ActGeProperty = ActGeProperty(alias, this)
    override fun `as`(alias: Table<*>): ActGeProperty = ActGeProperty(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): ActGeProperty = ActGeProperty(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): ActGeProperty = ActGeProperty(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): ActGeProperty = ActGeProperty(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): ActGeProperty =
        ActGeProperty(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): ActGeProperty = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): ActGeProperty = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): ActGeProperty = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(condition: SQL): ActGeProperty = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(@Stringly.SQL condition: String): ActGeProperty = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(@Stringly.SQL condition: String, vararg binds: Any?): ActGeProperty =
        where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): ActGeProperty =
        where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): ActGeProperty = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): ActGeProperty = where(DSL.notExists(select))
}
