/*
 * This file is generated by jOOQ.
 */
package emented.jooq.main.tables

import emented.jooq.main.Public
import emented.jooq.main.indexes.ACT_IDX_HI_INCIDENT_CREATE_TIME
import emented.jooq.main.indexes.ACT_IDX_HI_INCIDENT_END_TIME
import emented.jooq.main.indexes.ACT_IDX_HI_INCIDENT_PROCINST
import emented.jooq.main.indexes.ACT_IDX_HI_INCIDENT_PROC_DEF_KEY
import emented.jooq.main.indexes.ACT_IDX_HI_INCIDENT_RM_TIME
import emented.jooq.main.indexes.ACT_IDX_HI_INCIDENT_ROOT_PI
import emented.jooq.main.indexes.ACT_IDX_HI_INCIDENT_TENANT_ID
import emented.jooq.main.keys.ACT_HI_INCIDENT_PKEY
import emented.jooq.main.tables.records.ActHiIncidentRecord
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import java.time.LocalDateTime

/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ActHiIncident(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, ActHiIncidentRecord>?,
    parentPath: InverseForeignKey<out Record, ActHiIncidentRecord>?,
    aliased: Table<ActHiIncidentRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
) : TableImpl<ActHiIncidentRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.act_hi_incident</code>
         */
        val ACT_HI_INCIDENT: ActHiIncident = ActHiIncident()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<ActHiIncidentRecord> = ActHiIncidentRecord::class.java

    /**
     * The column <code>public.act_hi_incident.id_</code>.
     */
    val ID_: TableField<ActHiIncidentRecord, String?> =
        createField(DSL.name("id_"), SQLDataType.VARCHAR(64).nullable(false), this, "")

    /**
     * The column <code>public.act_hi_incident.proc_def_key_</code>.
     */
    val PROC_DEF_KEY_: TableField<ActHiIncidentRecord, String?> =
        createField(DSL.name("proc_def_key_"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.act_hi_incident.proc_def_id_</code>.
     */
    val PROC_DEF_ID_: TableField<ActHiIncidentRecord, String?> =
        createField(DSL.name("proc_def_id_"), SQLDataType.VARCHAR(64), this, "")

    /**
     * The column <code>public.act_hi_incident.root_proc_inst_id_</code>.
     */
    val ROOT_PROC_INST_ID_: TableField<ActHiIncidentRecord, String?> =
        createField(DSL.name("root_proc_inst_id_"), SQLDataType.VARCHAR(64), this, "")

    /**
     * The column <code>public.act_hi_incident.proc_inst_id_</code>.
     */
    val PROC_INST_ID_: TableField<ActHiIncidentRecord, String?> =
        createField(DSL.name("proc_inst_id_"), SQLDataType.VARCHAR(64), this, "")

    /**
     * The column <code>public.act_hi_incident.execution_id_</code>.
     */
    val EXECUTION_ID_: TableField<ActHiIncidentRecord, String?> =
        createField(DSL.name("execution_id_"), SQLDataType.VARCHAR(64), this, "")

    /**
     * The column <code>public.act_hi_incident.create_time_</code>.
     */
    val CREATE_TIME_: TableField<ActHiIncidentRecord, LocalDateTime?> =
        createField(DSL.name("create_time_"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    /**
     * The column <code>public.act_hi_incident.end_time_</code>.
     */
    val END_TIME_: TableField<ActHiIncidentRecord, LocalDateTime?> =
        createField(DSL.name("end_time_"), SQLDataType.LOCALDATETIME(6), this, "")

    /**
     * The column <code>public.act_hi_incident.incident_msg_</code>.
     */
    val INCIDENT_MSG_: TableField<ActHiIncidentRecord, String?> =
        createField(DSL.name("incident_msg_"), SQLDataType.VARCHAR(4000), this, "")

    /**
     * The column <code>public.act_hi_incident.incident_type_</code>.
     */
    val INCIDENT_TYPE_: TableField<ActHiIncidentRecord, String?> =
        createField(DSL.name("incident_type_"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>public.act_hi_incident.activity_id_</code>.
     */
    val ACTIVITY_ID_: TableField<ActHiIncidentRecord, String?> =
        createField(DSL.name("activity_id_"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.act_hi_incident.failed_activity_id_</code>.
     */
    val FAILED_ACTIVITY_ID_: TableField<ActHiIncidentRecord, String?> =
        createField(DSL.name("failed_activity_id_"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.act_hi_incident.cause_incident_id_</code>.
     */
    val CAUSE_INCIDENT_ID_: TableField<ActHiIncidentRecord, String?> =
        createField(DSL.name("cause_incident_id_"), SQLDataType.VARCHAR(64), this, "")

    /**
     * The column <code>public.act_hi_incident.root_cause_incident_id_</code>.
     */
    val ROOT_CAUSE_INCIDENT_ID_: TableField<ActHiIncidentRecord, String?> =
        createField(DSL.name("root_cause_incident_id_"), SQLDataType.VARCHAR(64), this, "")

    /**
     * The column <code>public.act_hi_incident.configuration_</code>.
     */
    val CONFIGURATION_: TableField<ActHiIncidentRecord, String?> =
        createField(DSL.name("configuration_"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.act_hi_incident.history_configuration_</code>.
     */
    val HISTORY_CONFIGURATION_: TableField<ActHiIncidentRecord, String?> =
        createField(DSL.name("history_configuration_"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.act_hi_incident.incident_state_</code>.
     */
    val INCIDENT_STATE_: TableField<ActHiIncidentRecord, Int?> =
        createField(DSL.name("incident_state_"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>public.act_hi_incident.tenant_id_</code>.
     */
    val TENANT_ID_: TableField<ActHiIncidentRecord, String?> =
        createField(DSL.name("tenant_id_"), SQLDataType.VARCHAR(64), this, "")

    /**
     * The column <code>public.act_hi_incident.job_def_id_</code>.
     */
    val JOB_DEF_ID_: TableField<ActHiIncidentRecord, String?> =
        createField(DSL.name("job_def_id_"), SQLDataType.VARCHAR(64), this, "")

    /**
     * The column <code>public.act_hi_incident.annotation_</code>.
     */
    val ANNOTATION_: TableField<ActHiIncidentRecord, String?> =
        createField(DSL.name("annotation_"), SQLDataType.VARCHAR(4000), this, "")

    /**
     * The column <code>public.act_hi_incident.removal_time_</code>.
     */
    val REMOVAL_TIME_: TableField<ActHiIncidentRecord, LocalDateTime?> =
        createField(DSL.name("removal_time_"), SQLDataType.LOCALDATETIME(6), this, "")

    private constructor(alias: Name, aliased: Table<ActHiIncidentRecord>?) : this(
        alias,
        null,
        null,
        null,
        aliased,
        null,
        null
    )

    private constructor(alias: Name, aliased: Table<ActHiIncidentRecord>?, parameters: Array<Field<*>?>?) : this(
        alias,
        null,
        null,
        null,
        aliased,
        parameters,
        null
    )

    private constructor(alias: Name, aliased: Table<ActHiIncidentRecord>?, where: Condition?) : this(
        alias,
        null,
        null,
        null,
        aliased,
        null,
        where
    )

    /**
     * Create an aliased <code>public.act_hi_incident</code> table reference
     */
    constructor(alias: String) : this(DSL.name(alias))

    /**
     * Create an aliased <code>public.act_hi_incident</code> table reference
     */
    constructor(alias: Name) : this(alias, null)

    /**
     * Create a <code>public.act_hi_incident</code> table reference
     */
    constructor() : this(DSL.name("act_hi_incident"), null)

    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(
        ACT_IDX_HI_INCIDENT_CREATE_TIME,
        ACT_IDX_HI_INCIDENT_END_TIME,
        ACT_IDX_HI_INCIDENT_PROC_DEF_KEY,
        ACT_IDX_HI_INCIDENT_PROCINST,
        ACT_IDX_HI_INCIDENT_RM_TIME,
        ACT_IDX_HI_INCIDENT_ROOT_PI,
        ACT_IDX_HI_INCIDENT_TENANT_ID
    )

    override fun getPrimaryKey(): UniqueKey<ActHiIncidentRecord> = ACT_HI_INCIDENT_PKEY
    override fun `as`(alias: String): ActHiIncident = ActHiIncident(DSL.name(alias), this)
    override fun `as`(alias: Name): ActHiIncident = ActHiIncident(alias, this)
    override fun `as`(alias: Table<*>): ActHiIncident = ActHiIncident(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): ActHiIncident = ActHiIncident(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): ActHiIncident = ActHiIncident(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): ActHiIncident = ActHiIncident(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): ActHiIncident =
        ActHiIncident(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): ActHiIncident = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): ActHiIncident = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): ActHiIncident = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(condition: SQL): ActHiIncident = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(@Stringly.SQL condition: String): ActHiIncident = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(@Stringly.SQL condition: String, vararg binds: Any?): ActHiIncident =
        where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): ActHiIncident =
        where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): ActHiIncident = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): ActHiIncident = where(DSL.notExists(select))
}
