/*
 * This file is generated by jOOQ.
 */
package emented.jooq.main.tables

import emented.jooq.main.Public
import emented.jooq.main.indexes.ACT_IDX_HI_IDENT_LINK_RM_TIME
import emented.jooq.main.indexes.ACT_IDX_HI_IDENT_LINK_TASK
import emented.jooq.main.indexes.ACT_IDX_HI_IDENT_LNK_GROUP
import emented.jooq.main.indexes.ACT_IDX_HI_IDENT_LNK_PROC_DEF_KEY
import emented.jooq.main.indexes.ACT_IDX_HI_IDENT_LNK_ROOT_PI
import emented.jooq.main.indexes.ACT_IDX_HI_IDENT_LNK_TENANT_ID
import emented.jooq.main.indexes.ACT_IDX_HI_IDENT_LNK_TIMESTAMP
import emented.jooq.main.indexes.ACT_IDX_HI_IDENT_LNK_USER
import emented.jooq.main.keys.ACT_HI_IDENTITYLINK_PKEY
import emented.jooq.main.tables.records.ActHiIdentitylinkRecord
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import java.time.LocalDateTime

/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ActHiIdentitylink(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, ActHiIdentitylinkRecord>?,
    parentPath: InverseForeignKey<out Record, ActHiIdentitylinkRecord>?,
    aliased: Table<ActHiIdentitylinkRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
) : TableImpl<ActHiIdentitylinkRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.act_hi_identitylink</code>
         */
        val ACT_HI_IDENTITYLINK: ActHiIdentitylink = ActHiIdentitylink()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<ActHiIdentitylinkRecord> = ActHiIdentitylinkRecord::class.java

    /**
     * The column <code>public.act_hi_identitylink.id_</code>.
     */
    val ID_: TableField<ActHiIdentitylinkRecord, String?> =
        createField(DSL.name("id_"), SQLDataType.VARCHAR(64).nullable(false), this, "")

    /**
     * The column <code>public.act_hi_identitylink.timestamp_</code>.
     */
    val TIMESTAMP_: TableField<ActHiIdentitylinkRecord, LocalDateTime?> =
        createField(DSL.name("timestamp_"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    /**
     * The column <code>public.act_hi_identitylink.type_</code>.
     */
    val TYPE_: TableField<ActHiIdentitylinkRecord, String?> =
        createField(DSL.name("type_"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.act_hi_identitylink.user_id_</code>.
     */
    val USER_ID_: TableField<ActHiIdentitylinkRecord, String?> =
        createField(DSL.name("user_id_"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.act_hi_identitylink.group_id_</code>.
     */
    val GROUP_ID_: TableField<ActHiIdentitylinkRecord, String?> =
        createField(DSL.name("group_id_"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.act_hi_identitylink.task_id_</code>.
     */
    val TASK_ID_: TableField<ActHiIdentitylinkRecord, String?> =
        createField(DSL.name("task_id_"), SQLDataType.VARCHAR(64), this, "")

    /**
     * The column <code>public.act_hi_identitylink.root_proc_inst_id_</code>.
     */
    val ROOT_PROC_INST_ID_: TableField<ActHiIdentitylinkRecord, String?> =
        createField(DSL.name("root_proc_inst_id_"), SQLDataType.VARCHAR(64), this, "")

    /**
     * The column <code>public.act_hi_identitylink.proc_def_id_</code>.
     */
    val PROC_DEF_ID_: TableField<ActHiIdentitylinkRecord, String?> =
        createField(DSL.name("proc_def_id_"), SQLDataType.VARCHAR(64), this, "")

    /**
     * The column <code>public.act_hi_identitylink.operation_type_</code>.
     */
    val OPERATION_TYPE_: TableField<ActHiIdentitylinkRecord, String?> =
        createField(DSL.name("operation_type_"), SQLDataType.VARCHAR(64), this, "")

    /**
     * The column <code>public.act_hi_identitylink.assigner_id_</code>.
     */
    val ASSIGNER_ID_: TableField<ActHiIdentitylinkRecord, String?> =
        createField(DSL.name("assigner_id_"), SQLDataType.VARCHAR(64), this, "")

    /**
     * The column <code>public.act_hi_identitylink.proc_def_key_</code>.
     */
    val PROC_DEF_KEY_: TableField<ActHiIdentitylinkRecord, String?> =
        createField(DSL.name("proc_def_key_"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.act_hi_identitylink.tenant_id_</code>.
     */
    val TENANT_ID_: TableField<ActHiIdentitylinkRecord, String?> =
        createField(DSL.name("tenant_id_"), SQLDataType.VARCHAR(64), this, "")

    /**
     * The column <code>public.act_hi_identitylink.removal_time_</code>.
     */
    val REMOVAL_TIME_: TableField<ActHiIdentitylinkRecord, LocalDateTime?> =
        createField(DSL.name("removal_time_"), SQLDataType.LOCALDATETIME(6), this, "")

    private constructor(alias: Name, aliased: Table<ActHiIdentitylinkRecord>?) : this(
        alias,
        null,
        null,
        null,
        aliased,
        null,
        null
    )

    private constructor(alias: Name, aliased: Table<ActHiIdentitylinkRecord>?, parameters: Array<Field<*>?>?) : this(
        alias,
        null,
        null,
        null,
        aliased,
        parameters,
        null
    )

    private constructor(alias: Name, aliased: Table<ActHiIdentitylinkRecord>?, where: Condition?) : this(
        alias,
        null,
        null,
        null,
        aliased,
        null,
        where
    )

    /**
     * Create an aliased <code>public.act_hi_identitylink</code> table reference
     */
    constructor(alias: String) : this(DSL.name(alias))

    /**
     * Create an aliased <code>public.act_hi_identitylink</code> table reference
     */
    constructor(alias: Name) : this(alias, null)

    /**
     * Create a <code>public.act_hi_identitylink</code> table reference
     */
    constructor() : this(DSL.name("act_hi_identitylink"), null)

    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(
        ACT_IDX_HI_IDENT_LINK_RM_TIME,
        ACT_IDX_HI_IDENT_LINK_TASK,
        ACT_IDX_HI_IDENT_LNK_GROUP,
        ACT_IDX_HI_IDENT_LNK_PROC_DEF_KEY,
        ACT_IDX_HI_IDENT_LNK_ROOT_PI,
        ACT_IDX_HI_IDENT_LNK_TENANT_ID,
        ACT_IDX_HI_IDENT_LNK_TIMESTAMP,
        ACT_IDX_HI_IDENT_LNK_USER
    )

    override fun getPrimaryKey(): UniqueKey<ActHiIdentitylinkRecord> = ACT_HI_IDENTITYLINK_PKEY
    override fun `as`(alias: String): ActHiIdentitylink = ActHiIdentitylink(DSL.name(alias), this)
    override fun `as`(alias: Name): ActHiIdentitylink = ActHiIdentitylink(alias, this)
    override fun `as`(alias: Table<*>): ActHiIdentitylink = ActHiIdentitylink(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): ActHiIdentitylink = ActHiIdentitylink(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): ActHiIdentitylink = ActHiIdentitylink(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): ActHiIdentitylink = ActHiIdentitylink(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): ActHiIdentitylink =
        ActHiIdentitylink(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): ActHiIdentitylink = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): ActHiIdentitylink = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): ActHiIdentitylink = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(condition: SQL): ActHiIdentitylink = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(@Stringly.SQL condition: String): ActHiIdentitylink = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(@Stringly.SQL condition: String, vararg binds: Any?): ActHiIdentitylink =
        where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): ActHiIdentitylink =
        where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): ActHiIdentitylink = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): ActHiIdentitylink = where(DSL.notExists(select))
}
