/*
 * This file is generated by jOOQ.
 */
package emented.jooq.main.tables

import emented.jooq.main.Public
import emented.jooq.main.indexes.ACT_HI_EXT_TASK_LOG_PROCDEF
import emented.jooq.main.indexes.ACT_HI_EXT_TASK_LOG_PROCINST
import emented.jooq.main.indexes.ACT_HI_EXT_TASK_LOG_PROC_DEF_KEY
import emented.jooq.main.indexes.ACT_HI_EXT_TASK_LOG_RM_TIME
import emented.jooq.main.indexes.ACT_HI_EXT_TASK_LOG_ROOT_PI
import emented.jooq.main.indexes.ACT_HI_EXT_TASK_LOG_TENANT_ID
import emented.jooq.main.indexes.ACT_IDX_HI_EXTTASKLOG_ERRORDET
import emented.jooq.main.keys.ACT_HI_EXT_TASK_LOG_PKEY
import emented.jooq.main.tables.records.ActHiExtTaskLogRecord
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import java.time.LocalDateTime

/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ActHiExtTaskLog(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, ActHiExtTaskLogRecord>?,
    parentPath: InverseForeignKey<out Record, ActHiExtTaskLogRecord>?,
    aliased: Table<ActHiExtTaskLogRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
) : TableImpl<ActHiExtTaskLogRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.act_hi_ext_task_log</code>
         */
        val ACT_HI_EXT_TASK_LOG: ActHiExtTaskLog = ActHiExtTaskLog()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<ActHiExtTaskLogRecord> = ActHiExtTaskLogRecord::class.java

    /**
     * The column <code>public.act_hi_ext_task_log.id_</code>.
     */
    val ID_: TableField<ActHiExtTaskLogRecord, String?> =
        createField(DSL.name("id_"), SQLDataType.VARCHAR(64).nullable(false), this, "")

    /**
     * The column <code>public.act_hi_ext_task_log.timestamp_</code>.
     */
    val TIMESTAMP_: TableField<ActHiExtTaskLogRecord, LocalDateTime?> =
        createField(DSL.name("timestamp_"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    /**
     * The column <code>public.act_hi_ext_task_log.ext_task_id_</code>.
     */
    val EXT_TASK_ID_: TableField<ActHiExtTaskLogRecord, String?> =
        createField(DSL.name("ext_task_id_"), SQLDataType.VARCHAR(64).nullable(false), this, "")

    /**
     * The column <code>public.act_hi_ext_task_log.retries_</code>.
     */
    val RETRIES_: TableField<ActHiExtTaskLogRecord, Int?> =
        createField(DSL.name("retries_"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>public.act_hi_ext_task_log.topic_name_</code>.
     */
    val TOPIC_NAME_: TableField<ActHiExtTaskLogRecord, String?> =
        createField(DSL.name("topic_name_"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.act_hi_ext_task_log.worker_id_</code>.
     */
    val WORKER_ID_: TableField<ActHiExtTaskLogRecord, String?> =
        createField(DSL.name("worker_id_"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.act_hi_ext_task_log.priority_</code>.
     */
    val PRIORITY_: TableField<ActHiExtTaskLogRecord, Long?> = createField(
        DSL.name("priority_"),
        SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)),
        this,
        ""
    )

    /**
     * The column <code>public.act_hi_ext_task_log.error_msg_</code>.
     */
    val ERROR_MSG_: TableField<ActHiExtTaskLogRecord, String?> =
        createField(DSL.name("error_msg_"), SQLDataType.VARCHAR(4000), this, "")

    /**
     * The column <code>public.act_hi_ext_task_log.error_details_id_</code>.
     */
    val ERROR_DETAILS_ID_: TableField<ActHiExtTaskLogRecord, String?> =
        createField(DSL.name("error_details_id_"), SQLDataType.VARCHAR(64), this, "")

    /**
     * The column <code>public.act_hi_ext_task_log.act_id_</code>.
     */
    val ACT_ID_: TableField<ActHiExtTaskLogRecord, String?> =
        createField(DSL.name("act_id_"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.act_hi_ext_task_log.act_inst_id_</code>.
     */
    val ACT_INST_ID_: TableField<ActHiExtTaskLogRecord, String?> =
        createField(DSL.name("act_inst_id_"), SQLDataType.VARCHAR(64), this, "")

    /**
     * The column <code>public.act_hi_ext_task_log.execution_id_</code>.
     */
    val EXECUTION_ID_: TableField<ActHiExtTaskLogRecord, String?> =
        createField(DSL.name("execution_id_"), SQLDataType.VARCHAR(64), this, "")

    /**
     * The column <code>public.act_hi_ext_task_log.proc_inst_id_</code>.
     */
    val PROC_INST_ID_: TableField<ActHiExtTaskLogRecord, String?> =
        createField(DSL.name("proc_inst_id_"), SQLDataType.VARCHAR(64), this, "")

    /**
     * The column <code>public.act_hi_ext_task_log.root_proc_inst_id_</code>.
     */
    val ROOT_PROC_INST_ID_: TableField<ActHiExtTaskLogRecord, String?> =
        createField(DSL.name("root_proc_inst_id_"), SQLDataType.VARCHAR(64), this, "")

    /**
     * The column <code>public.act_hi_ext_task_log.proc_def_id_</code>.
     */
    val PROC_DEF_ID_: TableField<ActHiExtTaskLogRecord, String?> =
        createField(DSL.name("proc_def_id_"), SQLDataType.VARCHAR(64), this, "")

    /**
     * The column <code>public.act_hi_ext_task_log.proc_def_key_</code>.
     */
    val PROC_DEF_KEY_: TableField<ActHiExtTaskLogRecord, String?> =
        createField(DSL.name("proc_def_key_"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.act_hi_ext_task_log.tenant_id_</code>.
     */
    val TENANT_ID_: TableField<ActHiExtTaskLogRecord, String?> =
        createField(DSL.name("tenant_id_"), SQLDataType.VARCHAR(64), this, "")

    /**
     * The column <code>public.act_hi_ext_task_log.state_</code>.
     */
    val STATE_: TableField<ActHiExtTaskLogRecord, Int?> = createField(DSL.name("state_"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>public.act_hi_ext_task_log.removal_time_</code>.
     */
    val REMOVAL_TIME_: TableField<ActHiExtTaskLogRecord, LocalDateTime?> =
        createField(DSL.name("removal_time_"), SQLDataType.LOCALDATETIME(6), this, "")

    private constructor(alias: Name, aliased: Table<ActHiExtTaskLogRecord>?) : this(
        alias,
        null,
        null,
        null,
        aliased,
        null,
        null
    )

    private constructor(
        alias: Name,
        aliased: Table<ActHiExtTaskLogRecord>?,
        parameters: Array<Field<*>?>?
    ) : this(alias, null, null, null, aliased, parameters, null)

    private constructor(alias: Name, aliased: Table<ActHiExtTaskLogRecord>?, where: Condition?) : this(
        alias,
        null,
        null,
        null,
        aliased,
        null,
        where
    )

    /**
     * Create an aliased <code>public.act_hi_ext_task_log</code> table reference
     */
    constructor(alias: String) : this(DSL.name(alias))

    /**
     * Create an aliased <code>public.act_hi_ext_task_log</code> table reference
     */
    constructor(alias: Name) : this(alias, null)

    /**
     * Create a <code>public.act_hi_ext_task_log</code> table reference
     */
    constructor() : this(DSL.name("act_hi_ext_task_log"), null)

    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(
        ACT_HI_EXT_TASK_LOG_PROC_DEF_KEY,
        ACT_HI_EXT_TASK_LOG_PROCDEF,
        ACT_HI_EXT_TASK_LOG_PROCINST,
        ACT_HI_EXT_TASK_LOG_RM_TIME,
        ACT_HI_EXT_TASK_LOG_ROOT_PI,
        ACT_HI_EXT_TASK_LOG_TENANT_ID,
        ACT_IDX_HI_EXTTASKLOG_ERRORDET
    )

    override fun getPrimaryKey(): UniqueKey<ActHiExtTaskLogRecord> = ACT_HI_EXT_TASK_LOG_PKEY
    override fun `as`(alias: String): ActHiExtTaskLog = ActHiExtTaskLog(DSL.name(alias), this)
    override fun `as`(alias: Name): ActHiExtTaskLog = ActHiExtTaskLog(alias, this)
    override fun `as`(alias: Table<*>): ActHiExtTaskLog = ActHiExtTaskLog(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): ActHiExtTaskLog = ActHiExtTaskLog(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): ActHiExtTaskLog = ActHiExtTaskLog(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): ActHiExtTaskLog = ActHiExtTaskLog(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): ActHiExtTaskLog =
        ActHiExtTaskLog(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): ActHiExtTaskLog = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): ActHiExtTaskLog = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): ActHiExtTaskLog = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(condition: SQL): ActHiExtTaskLog = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(@Stringly.SQL condition: String): ActHiExtTaskLog = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(@Stringly.SQL condition: String, vararg binds: Any?): ActHiExtTaskLog =
        where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): ActHiExtTaskLog =
        where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): ActHiExtTaskLog = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): ActHiExtTaskLog = where(DSL.notExists(select))
}
