/*
 * This file is generated by jOOQ.
 */
package emented.jooq.main.tables

import emented.jooq.main.Public
import emented.jooq.main.indexes.ACT_IDX_HI_CASEVAR_CASE_INST
import emented.jooq.main.indexes.ACT_IDX_HI_PROCVAR_NAME_TYPE
import emented.jooq.main.indexes.ACT_IDX_HI_PROCVAR_PROC_INST
import emented.jooq.main.indexes.ACT_IDX_HI_VARINST_ACT_INST_ID
import emented.jooq.main.indexes.ACT_IDX_HI_VARINST_BYTEAR
import emented.jooq.main.indexes.ACT_IDX_HI_VARINST_NAME
import emented.jooq.main.indexes.ACT_IDX_HI_VARINST_RM_TIME
import emented.jooq.main.indexes.ACT_IDX_HI_VARINST_ROOT_PI
import emented.jooq.main.indexes.ACT_IDX_HI_VAR_INST_PROC_DEF_KEY
import emented.jooq.main.indexes.ACT_IDX_HI_VAR_INST_TENANT_ID
import emented.jooq.main.indexes.ACT_IDX_HI_VAR_PI_NAME_TYPE
import emented.jooq.main.keys.ACT_HI_VARINST_PKEY
import emented.jooq.main.tables.records.ActHiVarinstRecord
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import java.time.LocalDateTime

/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ActHiVarinst(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, ActHiVarinstRecord>?,
    parentPath: InverseForeignKey<out Record, ActHiVarinstRecord>?,
    aliased: Table<ActHiVarinstRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
) : TableImpl<ActHiVarinstRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.act_hi_varinst</code>
         */
        val ACT_HI_VARINST: ActHiVarinst = ActHiVarinst()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<ActHiVarinstRecord> = ActHiVarinstRecord::class.java

    /**
     * The column <code>public.act_hi_varinst.id_</code>.
     */
    val ID_: TableField<ActHiVarinstRecord, String?> =
        createField(DSL.name("id_"), SQLDataType.VARCHAR(64).nullable(false), this, "")

    /**
     * The column <code>public.act_hi_varinst.proc_def_key_</code>.
     */
    val PROC_DEF_KEY_: TableField<ActHiVarinstRecord, String?> =
        createField(DSL.name("proc_def_key_"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.act_hi_varinst.proc_def_id_</code>.
     */
    val PROC_DEF_ID_: TableField<ActHiVarinstRecord, String?> =
        createField(DSL.name("proc_def_id_"), SQLDataType.VARCHAR(64), this, "")

    /**
     * The column <code>public.act_hi_varinst.root_proc_inst_id_</code>.
     */
    val ROOT_PROC_INST_ID_: TableField<ActHiVarinstRecord, String?> =
        createField(DSL.name("root_proc_inst_id_"), SQLDataType.VARCHAR(64), this, "")

    /**
     * The column <code>public.act_hi_varinst.proc_inst_id_</code>.
     */
    val PROC_INST_ID_: TableField<ActHiVarinstRecord, String?> =
        createField(DSL.name("proc_inst_id_"), SQLDataType.VARCHAR(64), this, "")

    /**
     * The column <code>public.act_hi_varinst.execution_id_</code>.
     */
    val EXECUTION_ID_: TableField<ActHiVarinstRecord, String?> =
        createField(DSL.name("execution_id_"), SQLDataType.VARCHAR(64), this, "")

    /**
     * The column <code>public.act_hi_varinst.act_inst_id_</code>.
     */
    val ACT_INST_ID_: TableField<ActHiVarinstRecord, String?> =
        createField(DSL.name("act_inst_id_"), SQLDataType.VARCHAR(64), this, "")

    /**
     * The column <code>public.act_hi_varinst.case_def_key_</code>.
     */
    val CASE_DEF_KEY_: TableField<ActHiVarinstRecord, String?> =
        createField(DSL.name("case_def_key_"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.act_hi_varinst.case_def_id_</code>.
     */
    val CASE_DEF_ID_: TableField<ActHiVarinstRecord, String?> =
        createField(DSL.name("case_def_id_"), SQLDataType.VARCHAR(64), this, "")

    /**
     * The column <code>public.act_hi_varinst.case_inst_id_</code>.
     */
    val CASE_INST_ID_: TableField<ActHiVarinstRecord, String?> =
        createField(DSL.name("case_inst_id_"), SQLDataType.VARCHAR(64), this, "")

    /**
     * The column <code>public.act_hi_varinst.case_execution_id_</code>.
     */
    val CASE_EXECUTION_ID_: TableField<ActHiVarinstRecord, String?> =
        createField(DSL.name("case_execution_id_"), SQLDataType.VARCHAR(64), this, "")

    /**
     * The column <code>public.act_hi_varinst.task_id_</code>.
     */
    val TASK_ID_: TableField<ActHiVarinstRecord, String?> =
        createField(DSL.name("task_id_"), SQLDataType.VARCHAR(64), this, "")

    /**
     * The column <code>public.act_hi_varinst.name_</code>.
     */
    val NAME_: TableField<ActHiVarinstRecord, String?> =
        createField(DSL.name("name_"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>public.act_hi_varinst.var_type_</code>.
     */
    val VAR_TYPE_: TableField<ActHiVarinstRecord, String?> =
        createField(DSL.name("var_type_"), SQLDataType.VARCHAR(100), this, "")

    /**
     * The column <code>public.act_hi_varinst.create_time_</code>.
     */
    val CREATE_TIME_: TableField<ActHiVarinstRecord, LocalDateTime?> =
        createField(DSL.name("create_time_"), SQLDataType.LOCALDATETIME(6), this, "")

    /**
     * The column <code>public.act_hi_varinst.rev_</code>.
     */
    val REV_: TableField<ActHiVarinstRecord, Int?> = createField(DSL.name("rev_"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>public.act_hi_varinst.bytearray_id_</code>.
     */
    val BYTEARRAY_ID_: TableField<ActHiVarinstRecord, String?> =
        createField(DSL.name("bytearray_id_"), SQLDataType.VARCHAR(64), this, "")

    /**
     * The column <code>public.act_hi_varinst.double_</code>.
     */
    val DOUBLE_: TableField<ActHiVarinstRecord, Double?> =
        createField(DSL.name("double_"), SQLDataType.DOUBLE, this, "")

    /**
     * The column <code>public.act_hi_varinst.long_</code>.
     */
    val LONG_: TableField<ActHiVarinstRecord, Long?> = createField(DSL.name("long_"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>public.act_hi_varinst.text_</code>.
     */
    val TEXT_: TableField<ActHiVarinstRecord, String?> =
        createField(DSL.name("text_"), SQLDataType.VARCHAR(4000), this, "")

    /**
     * The column <code>public.act_hi_varinst.text2_</code>.
     */
    val TEXT2_: TableField<ActHiVarinstRecord, String?> =
        createField(DSL.name("text2_"), SQLDataType.VARCHAR(4000), this, "")

    /**
     * The column <code>public.act_hi_varinst.tenant_id_</code>.
     */
    val TENANT_ID_: TableField<ActHiVarinstRecord, String?> =
        createField(DSL.name("tenant_id_"), SQLDataType.VARCHAR(64), this, "")

    /**
     * The column <code>public.act_hi_varinst.state_</code>.
     */
    val STATE_: TableField<ActHiVarinstRecord, String?> =
        createField(DSL.name("state_"), SQLDataType.VARCHAR(20), this, "")

    /**
     * The column <code>public.act_hi_varinst.removal_time_</code>.
     */
    val REMOVAL_TIME_: TableField<ActHiVarinstRecord, LocalDateTime?> =
        createField(DSL.name("removal_time_"), SQLDataType.LOCALDATETIME(6), this, "")

    private constructor(alias: Name, aliased: Table<ActHiVarinstRecord>?) : this(
        alias,
        null,
        null,
        null,
        aliased,
        null,
        null
    )

    private constructor(alias: Name, aliased: Table<ActHiVarinstRecord>?, parameters: Array<Field<*>?>?) : this(
        alias,
        null,
        null,
        null,
        aliased,
        parameters,
        null
    )

    private constructor(alias: Name, aliased: Table<ActHiVarinstRecord>?, where: Condition?) : this(
        alias,
        null,
        null,
        null,
        aliased,
        null,
        where
    )

    /**
     * Create an aliased <code>public.act_hi_varinst</code> table reference
     */
    constructor(alias: String) : this(DSL.name(alias))

    /**
     * Create an aliased <code>public.act_hi_varinst</code> table reference
     */
    constructor(alias: Name) : this(alias, null)

    /**
     * Create a <code>public.act_hi_varinst</code> table reference
     */
    constructor() : this(DSL.name("act_hi_varinst"), null)

    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(
        ACT_IDX_HI_CASEVAR_CASE_INST,
        ACT_IDX_HI_PROCVAR_NAME_TYPE,
        ACT_IDX_HI_PROCVAR_PROC_INST,
        ACT_IDX_HI_VAR_INST_PROC_DEF_KEY,
        ACT_IDX_HI_VAR_INST_TENANT_ID,
        ACT_IDX_HI_VAR_PI_NAME_TYPE,
        ACT_IDX_HI_VARINST_ACT_INST_ID,
        ACT_IDX_HI_VARINST_BYTEAR,
        ACT_IDX_HI_VARINST_NAME,
        ACT_IDX_HI_VARINST_RM_TIME,
        ACT_IDX_HI_VARINST_ROOT_PI
    )

    override fun getPrimaryKey(): UniqueKey<ActHiVarinstRecord> = ACT_HI_VARINST_PKEY
    override fun `as`(alias: String): ActHiVarinst = ActHiVarinst(DSL.name(alias), this)
    override fun `as`(alias: Name): ActHiVarinst = ActHiVarinst(alias, this)
    override fun `as`(alias: Table<*>): ActHiVarinst = ActHiVarinst(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): ActHiVarinst = ActHiVarinst(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): ActHiVarinst = ActHiVarinst(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): ActHiVarinst = ActHiVarinst(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): ActHiVarinst =
        ActHiVarinst(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): ActHiVarinst = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): ActHiVarinst = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): ActHiVarinst = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(condition: SQL): ActHiVarinst = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(@Stringly.SQL condition: String): ActHiVarinst = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(@Stringly.SQL condition: String, vararg binds: Any?): ActHiVarinst =
        where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): ActHiVarinst =
        where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): ActHiVarinst = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): ActHiVarinst = where(DSL.notExists(select))
}
