/*
 * This file is generated by jOOQ.
 */
package emented.jooq.main.tables

import emented.jooq.main.Public
import emented.jooq.main.indexes.ACT_IDX_HI_DEC_INST_ACT
import emented.jooq.main.indexes.ACT_IDX_HI_DEC_INST_ACT_INST
import emented.jooq.main.indexes.ACT_IDX_HI_DEC_INST_CI
import emented.jooq.main.indexes.ACT_IDX_HI_DEC_INST_ID
import emented.jooq.main.indexes.ACT_IDX_HI_DEC_INST_KEY
import emented.jooq.main.indexes.ACT_IDX_HI_DEC_INST_PI
import emented.jooq.main.indexes.ACT_IDX_HI_DEC_INST_REQ_ID
import emented.jooq.main.indexes.ACT_IDX_HI_DEC_INST_REQ_KEY
import emented.jooq.main.indexes.ACT_IDX_HI_DEC_INST_RM_TIME
import emented.jooq.main.indexes.ACT_IDX_HI_DEC_INST_ROOT_ID
import emented.jooq.main.indexes.ACT_IDX_HI_DEC_INST_ROOT_PI
import emented.jooq.main.indexes.ACT_IDX_HI_DEC_INST_TENANT_ID
import emented.jooq.main.indexes.ACT_IDX_HI_DEC_INST_TIME
import emented.jooq.main.keys.ACT_HI_DECINST_PKEY
import emented.jooq.main.tables.records.ActHiDecinstRecord
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import java.time.LocalDateTime

/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ActHiDecinst(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, ActHiDecinstRecord>?,
    parentPath: InverseForeignKey<out Record, ActHiDecinstRecord>?,
    aliased: Table<ActHiDecinstRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
) : TableImpl<ActHiDecinstRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.act_hi_decinst</code>
         */
        val ACT_HI_DECINST: ActHiDecinst = ActHiDecinst()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<ActHiDecinstRecord> = ActHiDecinstRecord::class.java

    /**
     * The column <code>public.act_hi_decinst.id_</code>.
     */
    val ID_: TableField<ActHiDecinstRecord, String?> =
        createField(DSL.name("id_"), SQLDataType.VARCHAR(64).nullable(false), this, "")

    /**
     * The column <code>public.act_hi_decinst.dec_def_id_</code>.
     */
    val DEC_DEF_ID_: TableField<ActHiDecinstRecord, String?> =
        createField(DSL.name("dec_def_id_"), SQLDataType.VARCHAR(64).nullable(false), this, "")

    /**
     * The column <code>public.act_hi_decinst.dec_def_key_</code>.
     */
    val DEC_DEF_KEY_: TableField<ActHiDecinstRecord, String?> =
        createField(DSL.name("dec_def_key_"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>public.act_hi_decinst.dec_def_name_</code>.
     */
    val DEC_DEF_NAME_: TableField<ActHiDecinstRecord, String?> =
        createField(DSL.name("dec_def_name_"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.act_hi_decinst.proc_def_key_</code>.
     */
    val PROC_DEF_KEY_: TableField<ActHiDecinstRecord, String?> =
        createField(DSL.name("proc_def_key_"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.act_hi_decinst.proc_def_id_</code>.
     */
    val PROC_DEF_ID_: TableField<ActHiDecinstRecord, String?> =
        createField(DSL.name("proc_def_id_"), SQLDataType.VARCHAR(64), this, "")

    /**
     * The column <code>public.act_hi_decinst.proc_inst_id_</code>.
     */
    val PROC_INST_ID_: TableField<ActHiDecinstRecord, String?> =
        createField(DSL.name("proc_inst_id_"), SQLDataType.VARCHAR(64), this, "")

    /**
     * The column <code>public.act_hi_decinst.case_def_key_</code>.
     */
    val CASE_DEF_KEY_: TableField<ActHiDecinstRecord, String?> =
        createField(DSL.name("case_def_key_"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.act_hi_decinst.case_def_id_</code>.
     */
    val CASE_DEF_ID_: TableField<ActHiDecinstRecord, String?> =
        createField(DSL.name("case_def_id_"), SQLDataType.VARCHAR(64), this, "")

    /**
     * The column <code>public.act_hi_decinst.case_inst_id_</code>.
     */
    val CASE_INST_ID_: TableField<ActHiDecinstRecord, String?> =
        createField(DSL.name("case_inst_id_"), SQLDataType.VARCHAR(64), this, "")

    /**
     * The column <code>public.act_hi_decinst.act_inst_id_</code>.
     */
    val ACT_INST_ID_: TableField<ActHiDecinstRecord, String?> =
        createField(DSL.name("act_inst_id_"), SQLDataType.VARCHAR(64), this, "")

    /**
     * The column <code>public.act_hi_decinst.act_id_</code>.
     */
    val ACT_ID_: TableField<ActHiDecinstRecord, String?> =
        createField(DSL.name("act_id_"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.act_hi_decinst.eval_time_</code>.
     */
    val EVAL_TIME_: TableField<ActHiDecinstRecord, LocalDateTime?> =
        createField(DSL.name("eval_time_"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    /**
     * The column <code>public.act_hi_decinst.removal_time_</code>.
     */
    val REMOVAL_TIME_: TableField<ActHiDecinstRecord, LocalDateTime?> =
        createField(DSL.name("removal_time_"), SQLDataType.LOCALDATETIME(6), this, "")

    /**
     * The column <code>public.act_hi_decinst.collect_value_</code>.
     */
    val COLLECT_VALUE_: TableField<ActHiDecinstRecord, Double?> =
        createField(DSL.name("collect_value_"), SQLDataType.DOUBLE, this, "")

    /**
     * The column <code>public.act_hi_decinst.user_id_</code>.
     */
    val USER_ID_: TableField<ActHiDecinstRecord, String?> =
        createField(DSL.name("user_id_"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.act_hi_decinst.root_dec_inst_id_</code>.
     */
    val ROOT_DEC_INST_ID_: TableField<ActHiDecinstRecord, String?> =
        createField(DSL.name("root_dec_inst_id_"), SQLDataType.VARCHAR(64), this, "")

    /**
     * The column <code>public.act_hi_decinst.root_proc_inst_id_</code>.
     */
    val ROOT_PROC_INST_ID_: TableField<ActHiDecinstRecord, String?> =
        createField(DSL.name("root_proc_inst_id_"), SQLDataType.VARCHAR(64), this, "")

    /**
     * The column <code>public.act_hi_decinst.dec_req_id_</code>.
     */
    val DEC_REQ_ID_: TableField<ActHiDecinstRecord, String?> =
        createField(DSL.name("dec_req_id_"), SQLDataType.VARCHAR(64), this, "")

    /**
     * The column <code>public.act_hi_decinst.dec_req_key_</code>.
     */
    val DEC_REQ_KEY_: TableField<ActHiDecinstRecord, String?> =
        createField(DSL.name("dec_req_key_"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.act_hi_decinst.tenant_id_</code>.
     */
    val TENANT_ID_: TableField<ActHiDecinstRecord, String?> =
        createField(DSL.name("tenant_id_"), SQLDataType.VARCHAR(64), this, "")

    private constructor(alias: Name, aliased: Table<ActHiDecinstRecord>?) : this(
        alias,
        null,
        null,
        null,
        aliased,
        null,
        null
    )

    private constructor(alias: Name, aliased: Table<ActHiDecinstRecord>?, parameters: Array<Field<*>?>?) : this(
        alias,
        null,
        null,
        null,
        aliased,
        parameters,
        null
    )

    private constructor(alias: Name, aliased: Table<ActHiDecinstRecord>?, where: Condition?) : this(
        alias,
        null,
        null,
        null,
        aliased,
        null,
        where
    )

    /**
     * Create an aliased <code>public.act_hi_decinst</code> table reference
     */
    constructor(alias: String) : this(DSL.name(alias))

    /**
     * Create an aliased <code>public.act_hi_decinst</code> table reference
     */
    constructor(alias: Name) : this(alias, null)

    /**
     * Create a <code>public.act_hi_decinst</code> table reference
     */
    constructor() : this(DSL.name("act_hi_decinst"), null)

    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(
        ACT_IDX_HI_DEC_INST_ACT,
        ACT_IDX_HI_DEC_INST_ACT_INST,
        ACT_IDX_HI_DEC_INST_CI,
        ACT_IDX_HI_DEC_INST_ID,
        ACT_IDX_HI_DEC_INST_KEY,
        ACT_IDX_HI_DEC_INST_PI,
        ACT_IDX_HI_DEC_INST_REQ_ID,
        ACT_IDX_HI_DEC_INST_REQ_KEY,
        ACT_IDX_HI_DEC_INST_RM_TIME,
        ACT_IDX_HI_DEC_INST_ROOT_ID,
        ACT_IDX_HI_DEC_INST_ROOT_PI,
        ACT_IDX_HI_DEC_INST_TENANT_ID,
        ACT_IDX_HI_DEC_INST_TIME
    )

    override fun getPrimaryKey(): UniqueKey<ActHiDecinstRecord> = ACT_HI_DECINST_PKEY
    override fun `as`(alias: String): ActHiDecinst = ActHiDecinst(DSL.name(alias), this)
    override fun `as`(alias: Name): ActHiDecinst = ActHiDecinst(alias, this)
    override fun `as`(alias: Table<*>): ActHiDecinst = ActHiDecinst(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): ActHiDecinst = ActHiDecinst(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): ActHiDecinst = ActHiDecinst(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): ActHiDecinst = ActHiDecinst(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): ActHiDecinst =
        ActHiDecinst(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): ActHiDecinst = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): ActHiDecinst = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): ActHiDecinst = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(condition: SQL): ActHiDecinst = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(@Stringly.SQL condition: String): ActHiDecinst = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(@Stringly.SQL condition: String, vararg binds: Any?): ActHiDecinst =
        where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): ActHiDecinst =
        where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): ActHiDecinst = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): ActHiDecinst = where(DSL.notExists(select))
}
