/*
 * This file is generated by jOOQ.
 */
package emented.jooq.main.tables

import emented.jooq.main.Public
import emented.jooq.main.keys.ACT_ID_INFO_PKEY
import emented.jooq.main.tables.records.ActIdInfoRecord
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl

/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ActIdInfo(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, ActIdInfoRecord>?,
    parentPath: InverseForeignKey<out Record, ActIdInfoRecord>?,
    aliased: Table<ActIdInfoRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
) : TableImpl<ActIdInfoRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.act_id_info</code>
         */
        val ACT_ID_INFO: ActIdInfo = ActIdInfo()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<ActIdInfoRecord> = ActIdInfoRecord::class.java

    /**
     * The column <code>public.act_id_info.id_</code>.
     */
    val ID_: TableField<ActIdInfoRecord, String?> =
        createField(DSL.name("id_"), SQLDataType.VARCHAR(64).nullable(false), this, "")

    /**
     * The column <code>public.act_id_info.rev_</code>.
     */
    val REV_: TableField<ActIdInfoRecord, Int?> = createField(DSL.name("rev_"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>public.act_id_info.user_id_</code>.
     */
    val USER_ID_: TableField<ActIdInfoRecord, String?> =
        createField(DSL.name("user_id_"), SQLDataType.VARCHAR(64), this, "")

    /**
     * The column <code>public.act_id_info.type_</code>.
     */
    val TYPE_: TableField<ActIdInfoRecord, String?> = createField(DSL.name("type_"), SQLDataType.VARCHAR(64), this, "")

    /**
     * The column <code>public.act_id_info.key_</code>.
     */
    val KEY_: TableField<ActIdInfoRecord, String?> = createField(DSL.name("key_"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.act_id_info.value_</code>.
     */
    val VALUE_: TableField<ActIdInfoRecord, String?> =
        createField(DSL.name("value_"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.act_id_info.password_</code>.
     */
    val PASSWORD_: TableField<ActIdInfoRecord, ByteArray?> =
        createField(DSL.name("password_"), SQLDataType.BLOB, this, "")

    /**
     * The column <code>public.act_id_info.parent_id_</code>.
     */
    val PARENT_ID_: TableField<ActIdInfoRecord, String?> =
        createField(DSL.name("parent_id_"), SQLDataType.VARCHAR(255), this, "")

    private constructor(alias: Name, aliased: Table<ActIdInfoRecord>?) : this(
        alias,
        null,
        null,
        null,
        aliased,
        null,
        null
    )

    private constructor(alias: Name, aliased: Table<ActIdInfoRecord>?, parameters: Array<Field<*>?>?) : this(
        alias,
        null,
        null,
        null,
        aliased,
        parameters,
        null
    )

    private constructor(alias: Name, aliased: Table<ActIdInfoRecord>?, where: Condition?) : this(
        alias,
        null,
        null,
        null,
        aliased,
        null,
        where
    )

    /**
     * Create an aliased <code>public.act_id_info</code> table reference
     */
    constructor(alias: String) : this(DSL.name(alias))

    /**
     * Create an aliased <code>public.act_id_info</code> table reference
     */
    constructor(alias: Name) : this(alias, null)

    /**
     * Create a <code>public.act_id_info</code> table reference
     */
    constructor() : this(DSL.name("act_id_info"), null)

    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<ActIdInfoRecord> = ACT_ID_INFO_PKEY
    override fun `as`(alias: String): ActIdInfo = ActIdInfo(DSL.name(alias), this)
    override fun `as`(alias: Name): ActIdInfo = ActIdInfo(alias, this)
    override fun `as`(alias: Table<*>): ActIdInfo = ActIdInfo(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): ActIdInfo = ActIdInfo(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): ActIdInfo = ActIdInfo(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): ActIdInfo = ActIdInfo(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): ActIdInfo =
        ActIdInfo(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): ActIdInfo = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): ActIdInfo = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): ActIdInfo = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(condition: SQL): ActIdInfo = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(@Stringly.SQL condition: String): ActIdInfo = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(@Stringly.SQL condition: String, vararg binds: Any?): ActIdInfo =
        where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): ActIdInfo =
        where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): ActIdInfo = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): ActIdInfo = where(DSL.notExists(select))
}
