/*
 * This file is generated by jOOQ.
 */
package emented.jooq.main.tables

import emented.jooq.main.Public
import emented.jooq.main.keys.ACT_ID_MEMBERSHIP__ACT_FK_MEMB_USER
import emented.jooq.main.keys.ACT_ID_TENANT_MEMBER__ACT_FK_TENANT_MEMB_USER
import emented.jooq.main.keys.ACT_ID_USER_PKEY
import emented.jooq.main.tables.ActIdGroup.ActIdGroupPath
import emented.jooq.main.tables.ActIdMembership.ActIdMembershipPath
import emented.jooq.main.tables.ActIdTenant.ActIdTenantPath
import emented.jooq.main.tables.ActIdTenantMember.ActIdTenantMemberPath
import emented.jooq.main.tables.records.ActIdUserRecord
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import java.time.LocalDateTime

/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ActIdUser(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, ActIdUserRecord>?,
    parentPath: InverseForeignKey<out Record, ActIdUserRecord>?,
    aliased: Table<ActIdUserRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
) : TableImpl<ActIdUserRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.act_id_user</code>
         */
        val ACT_ID_USER: ActIdUser = ActIdUser()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<ActIdUserRecord> = ActIdUserRecord::class.java

    /**
     * The column <code>public.act_id_user.id_</code>.
     */
    val ID_: TableField<ActIdUserRecord, String?> =
        createField(DSL.name("id_"), SQLDataType.VARCHAR(64).nullable(false), this, "")

    /**
     * The column <code>public.act_id_user.rev_</code>.
     */
    val REV_: TableField<ActIdUserRecord, Int?> = createField(DSL.name("rev_"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>public.act_id_user.first_</code>.
     */
    val FIRST_: TableField<ActIdUserRecord, String?> =
        createField(DSL.name("first_"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.act_id_user.last_</code>.
     */
    val LAST_: TableField<ActIdUserRecord, String?> = createField(DSL.name("last_"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.act_id_user.email_</code>.
     */
    val EMAIL_: TableField<ActIdUserRecord, String?> =
        createField(DSL.name("email_"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.act_id_user.pwd_</code>.
     */
    val PWD_: TableField<ActIdUserRecord, String?> = createField(DSL.name("pwd_"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.act_id_user.salt_</code>.
     */
    val SALT_: TableField<ActIdUserRecord, String?> = createField(DSL.name("salt_"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.act_id_user.lock_exp_time_</code>.
     */
    val LOCK_EXP_TIME_: TableField<ActIdUserRecord, LocalDateTime?> =
        createField(DSL.name("lock_exp_time_"), SQLDataType.LOCALDATETIME(6), this, "")

    /**
     * The column <code>public.act_id_user.attempts_</code>.
     */
    val ATTEMPTS_: TableField<ActIdUserRecord, Int?> = createField(DSL.name("attempts_"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>public.act_id_user.picture_id_</code>.
     */
    val PICTURE_ID_: TableField<ActIdUserRecord, String?> =
        createField(DSL.name("picture_id_"), SQLDataType.VARCHAR(64), this, "")

    private constructor(alias: Name, aliased: Table<ActIdUserRecord>?) : this(
        alias,
        null,
        null,
        null,
        aliased,
        null,
        null
    )

    private constructor(alias: Name, aliased: Table<ActIdUserRecord>?, parameters: Array<Field<*>?>?) : this(
        alias,
        null,
        null,
        null,
        aliased,
        parameters,
        null
    )

    private constructor(alias: Name, aliased: Table<ActIdUserRecord>?, where: Condition?) : this(
        alias,
        null,
        null,
        null,
        aliased,
        null,
        where
    )

    /**
     * Create an aliased <code>public.act_id_user</code> table reference
     */
    constructor(alias: String) : this(DSL.name(alias))

    /**
     * Create an aliased <code>public.act_id_user</code> table reference
     */
    constructor(alias: Name) : this(alias, null)

    /**
     * Create a <code>public.act_id_user</code> table reference
     */
    constructor() : this(DSL.name("act_id_user"), null)

    constructor(
        path: Table<out Record>,
        childPath: ForeignKey<out Record, ActIdUserRecord>?,
        parentPath: InverseForeignKey<out Record, ActIdUserRecord>?
    ) : this(
        Internal.createPathAlias(path, childPath, parentPath),
        path,
        childPath,
        parentPath,
        ACT_ID_USER,
        null,
        null
    )

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class ActIdUserPath : ActIdUser, Path<ActIdUserRecord> {
        constructor(
            path: Table<out Record>,
            childPath: ForeignKey<out Record, ActIdUserRecord>?,
            parentPath: InverseForeignKey<out Record, ActIdUserRecord>?
        ) : super(path, childPath, parentPath)

        private constructor(alias: Name, aliased: Table<ActIdUserRecord>) : super(alias, aliased)

        override fun `as`(alias: String): ActIdUserPath = ActIdUserPath(DSL.name(alias), this)
        override fun `as`(alias: Name): ActIdUserPath = ActIdUserPath(alias, this)
        override fun `as`(alias: Table<*>): ActIdUserPath = ActIdUserPath(alias.qualifiedName, this)
    }

    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<ActIdUserRecord> = ACT_ID_USER_PKEY

    private lateinit var _actIdMembership: ActIdMembershipPath

    /**
     * Get the implicit to-many join path to the
     * <code>public.act_id_membership</code> table
     */
    fun actIdMembership(): ActIdMembershipPath {
        if (!this::_actIdMembership.isInitialized)
            _actIdMembership = ActIdMembershipPath(this, null, ACT_ID_MEMBERSHIP__ACT_FK_MEMB_USER.inverseKey)

        return _actIdMembership
    }

    val actIdMembership: ActIdMembershipPath
        get(): ActIdMembershipPath = actIdMembership()

    private lateinit var _actIdTenantMember: ActIdTenantMemberPath

    /**
     * Get the implicit to-many join path to the
     * <code>public.act_id_tenant_member</code> table
     */
    fun actIdTenantMember(): ActIdTenantMemberPath {
        if (!this::_actIdTenantMember.isInitialized)
            _actIdTenantMember =
                ActIdTenantMemberPath(this, null, ACT_ID_TENANT_MEMBER__ACT_FK_TENANT_MEMB_USER.inverseKey)

        return _actIdTenantMember
    }

    val actIdTenantMember: ActIdTenantMemberPath
        get(): ActIdTenantMemberPath = actIdTenantMember()

    /**
     * Get the implicit many-to-many join path to the
     * <code>public.act_id_group</code> table
     */
    val actIdGroup: ActIdGroupPath
        get(): ActIdGroupPath = actIdMembership().actIdGroup()

    /**
     * Get the implicit many-to-many join path to the
     * <code>public.act_id_tenant</code> table
     */
    val actIdTenant: ActIdTenantPath
        get(): ActIdTenantPath = actIdTenantMember().actIdTenant()

    override fun `as`(alias: String): ActIdUser = ActIdUser(DSL.name(alias), this)
    override fun `as`(alias: Name): ActIdUser = ActIdUser(alias, this)
    override fun `as`(alias: Table<*>): ActIdUser = ActIdUser(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): ActIdUser = ActIdUser(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): ActIdUser = ActIdUser(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): ActIdUser = ActIdUser(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): ActIdUser =
        ActIdUser(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): ActIdUser = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): ActIdUser = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): ActIdUser = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(condition: SQL): ActIdUser = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(@Stringly.SQL condition: String): ActIdUser = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(@Stringly.SQL condition: String, vararg binds: Any?): ActIdUser =
        where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): ActIdUser =
        where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): ActIdUser = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): ActIdUser = where(DSL.notExists(select))
}
