/*
 * This file is generated by jOOQ.
 */
package emented.jooq.main.tables

import emented.jooq.main.Public
import emented.jooq.main.indexes.ACT_IDX_TENANT_MEMB
import emented.jooq.main.indexes.ACT_IDX_TENANT_MEMB_GROUP
import emented.jooq.main.indexes.ACT_IDX_TENANT_MEMB_USER
import emented.jooq.main.keys.ACT_ID_TENANT_MEMBER_PKEY
import emented.jooq.main.keys.ACT_ID_TENANT_MEMBER__ACT_FK_TENANT_MEMB
import emented.jooq.main.keys.ACT_ID_TENANT_MEMBER__ACT_FK_TENANT_MEMB_GROUP
import emented.jooq.main.keys.ACT_ID_TENANT_MEMBER__ACT_FK_TENANT_MEMB_USER
import emented.jooq.main.keys.ACT_UNIQ_TENANT_MEMB_GROUP
import emented.jooq.main.keys.ACT_UNIQ_TENANT_MEMB_USER
import emented.jooq.main.tables.ActIdGroup.ActIdGroupPath
import emented.jooq.main.tables.ActIdTenant.ActIdTenantPath
import emented.jooq.main.tables.ActIdUser.ActIdUserPath
import emented.jooq.main.tables.records.ActIdTenantMemberRecord
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl

/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ActIdTenantMember(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, ActIdTenantMemberRecord>?,
    parentPath: InverseForeignKey<out Record, ActIdTenantMemberRecord>?,
    aliased: Table<ActIdTenantMemberRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
) : TableImpl<ActIdTenantMemberRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.act_id_tenant_member</code>
         */
        val ACT_ID_TENANT_MEMBER: ActIdTenantMember = ActIdTenantMember()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<ActIdTenantMemberRecord> = ActIdTenantMemberRecord::class.java

    /**
     * The column <code>public.act_id_tenant_member.id_</code>.
     */
    val ID_: TableField<ActIdTenantMemberRecord, String?> =
        createField(DSL.name("id_"), SQLDataType.VARCHAR(64).nullable(false), this, "")

    /**
     * The column <code>public.act_id_tenant_member.tenant_id_</code>.
     */
    val TENANT_ID_: TableField<ActIdTenantMemberRecord, String?> =
        createField(DSL.name("tenant_id_"), SQLDataType.VARCHAR(64).nullable(false), this, "")

    /**
     * The column <code>public.act_id_tenant_member.user_id_</code>.
     */
    val USER_ID_: TableField<ActIdTenantMemberRecord, String?> =
        createField(DSL.name("user_id_"), SQLDataType.VARCHAR(64), this, "")

    /**
     * The column <code>public.act_id_tenant_member.group_id_</code>.
     */
    val GROUP_ID_: TableField<ActIdTenantMemberRecord, String?> =
        createField(DSL.name("group_id_"), SQLDataType.VARCHAR(64), this, "")

    private constructor(alias: Name, aliased: Table<ActIdTenantMemberRecord>?) : this(
        alias,
        null,
        null,
        null,
        aliased,
        null,
        null
    )

    private constructor(alias: Name, aliased: Table<ActIdTenantMemberRecord>?, parameters: Array<Field<*>?>?) : this(
        alias,
        null,
        null,
        null,
        aliased,
        parameters,
        null
    )

    private constructor(alias: Name, aliased: Table<ActIdTenantMemberRecord>?, where: Condition?) : this(
        alias,
        null,
        null,
        null,
        aliased,
        null,
        where
    )

    /**
     * Create an aliased <code>public.act_id_tenant_member</code> table
     * reference
     */
    constructor(alias: String) : this(DSL.name(alias))

    /**
     * Create an aliased <code>public.act_id_tenant_member</code> table
     * reference
     */
    constructor(alias: Name) : this(alias, null)

    /**
     * Create a <code>public.act_id_tenant_member</code> table reference
     */
    constructor() : this(DSL.name("act_id_tenant_member"), null)

    constructor(
        path: Table<out Record>,
        childPath: ForeignKey<out Record, ActIdTenantMemberRecord>?,
        parentPath: InverseForeignKey<out Record, ActIdTenantMemberRecord>?
    ) : this(
        Internal.createPathAlias(path, childPath, parentPath),
        path,
        childPath,
        parentPath,
        ACT_ID_TENANT_MEMBER,
        null,
        null
    )

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class ActIdTenantMemberPath : ActIdTenantMember, Path<ActIdTenantMemberRecord> {
        constructor(
            path: Table<out Record>,
            childPath: ForeignKey<out Record, ActIdTenantMemberRecord>?,
            parentPath: InverseForeignKey<out Record, ActIdTenantMemberRecord>?
        ) : super(path, childPath, parentPath)

        private constructor(alias: Name, aliased: Table<ActIdTenantMemberRecord>) : super(alias, aliased)

        override fun `as`(alias: String): ActIdTenantMemberPath = ActIdTenantMemberPath(DSL.name(alias), this)
        override fun `as`(alias: Name): ActIdTenantMemberPath = ActIdTenantMemberPath(alias, this)
        override fun `as`(alias: Table<*>): ActIdTenantMemberPath = ActIdTenantMemberPath(alias.qualifiedName, this)
    }

    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> =
        listOf(ACT_IDX_TENANT_MEMB, ACT_IDX_TENANT_MEMB_GROUP, ACT_IDX_TENANT_MEMB_USER)

    override fun getPrimaryKey(): UniqueKey<ActIdTenantMemberRecord> = ACT_ID_TENANT_MEMBER_PKEY
    override fun getUniqueKeys(): List<UniqueKey<ActIdTenantMemberRecord>> =
        listOf(ACT_UNIQ_TENANT_MEMB_GROUP, ACT_UNIQ_TENANT_MEMB_USER)

    override fun getReferences(): List<ForeignKey<ActIdTenantMemberRecord, *>> = listOf(
        ACT_ID_TENANT_MEMBER__ACT_FK_TENANT_MEMB,
        ACT_ID_TENANT_MEMBER__ACT_FK_TENANT_MEMB_USER,
        ACT_ID_TENANT_MEMBER__ACT_FK_TENANT_MEMB_GROUP
    )

    private lateinit var _actIdTenant: ActIdTenantPath

    /**
     * Get the implicit join path to the <code>public.act_id_tenant</code>
     * table.
     */
    fun actIdTenant(): ActIdTenantPath {
        if (!this::_actIdTenant.isInitialized)
            _actIdTenant = ActIdTenantPath(this, ACT_ID_TENANT_MEMBER__ACT_FK_TENANT_MEMB, null)

        return _actIdTenant
    }

    val actIdTenant: ActIdTenantPath
        get(): ActIdTenantPath = actIdTenant()

    private lateinit var _actIdUser: ActIdUserPath

    /**
     * Get the implicit join path to the <code>public.act_id_user</code> table.
     */
    fun actIdUser(): ActIdUserPath {
        if (!this::_actIdUser.isInitialized)
            _actIdUser = ActIdUserPath(this, ACT_ID_TENANT_MEMBER__ACT_FK_TENANT_MEMB_USER, null)

        return _actIdUser
    }

    val actIdUser: ActIdUserPath
        get(): ActIdUserPath = actIdUser()

    private lateinit var _actIdGroup: ActIdGroupPath

    /**
     * Get the implicit join path to the <code>public.act_id_group</code> table.
     */
    fun actIdGroup(): ActIdGroupPath {
        if (!this::_actIdGroup.isInitialized)
            _actIdGroup = ActIdGroupPath(this, ACT_ID_TENANT_MEMBER__ACT_FK_TENANT_MEMB_GROUP, null)

        return _actIdGroup
    }

    val actIdGroup: ActIdGroupPath
        get(): ActIdGroupPath = actIdGroup()

    override fun `as`(alias: String): ActIdTenantMember = ActIdTenantMember(DSL.name(alias), this)
    override fun `as`(alias: Name): ActIdTenantMember = ActIdTenantMember(alias, this)
    override fun `as`(alias: Table<*>): ActIdTenantMember = ActIdTenantMember(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): ActIdTenantMember = ActIdTenantMember(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): ActIdTenantMember = ActIdTenantMember(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): ActIdTenantMember = ActIdTenantMember(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): ActIdTenantMember =
        ActIdTenantMember(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): ActIdTenantMember = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): ActIdTenantMember = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): ActIdTenantMember = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(condition: SQL): ActIdTenantMember = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(@Stringly.SQL condition: String): ActIdTenantMember = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(@Stringly.SQL condition: String, vararg binds: Any?): ActIdTenantMember =
        where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): ActIdTenantMember =
        where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): ActIdTenantMember = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): ActIdTenantMember = where(DSL.notExists(select))
}
