/*
 * This file is generated by jOOQ.
 */
package emented.jooq.main.tables

import emented.jooq.main.Public
import emented.jooq.main.keys.ACT_ID_TENANT_MEMBER__ACT_FK_TENANT_MEMB
import emented.jooq.main.keys.ACT_ID_TENANT_PKEY
import emented.jooq.main.tables.ActIdGroup.ActIdGroupPath
import emented.jooq.main.tables.ActIdTenantMember.ActIdTenantMemberPath
import emented.jooq.main.tables.ActIdUser.ActIdUserPath
import emented.jooq.main.tables.records.ActIdTenantRecord
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl

/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ActIdTenant(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, ActIdTenantRecord>?,
    parentPath: InverseForeignKey<out Record, ActIdTenantRecord>?,
    aliased: Table<ActIdTenantRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
) : TableImpl<ActIdTenantRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.act_id_tenant</code>
         */
        val ACT_ID_TENANT: ActIdTenant = ActIdTenant()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<ActIdTenantRecord> = ActIdTenantRecord::class.java

    /**
     * The column <code>public.act_id_tenant.id_</code>.
     */
    val ID_: TableField<ActIdTenantRecord, String?> =
        createField(DSL.name("id_"), SQLDataType.VARCHAR(64).nullable(false), this, "")

    /**
     * The column <code>public.act_id_tenant.rev_</code>.
     */
    val REV_: TableField<ActIdTenantRecord, Int?> = createField(DSL.name("rev_"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>public.act_id_tenant.name_</code>.
     */
    val NAME_: TableField<ActIdTenantRecord, String?> =
        createField(DSL.name("name_"), SQLDataType.VARCHAR(255), this, "")

    private constructor(alias: Name, aliased: Table<ActIdTenantRecord>?) : this(
        alias,
        null,
        null,
        null,
        aliased,
        null,
        null
    )

    private constructor(alias: Name, aliased: Table<ActIdTenantRecord>?, parameters: Array<Field<*>?>?) : this(
        alias,
        null,
        null,
        null,
        aliased,
        parameters,
        null
    )

    private constructor(alias: Name, aliased: Table<ActIdTenantRecord>?, where: Condition?) : this(
        alias,
        null,
        null,
        null,
        aliased,
        null,
        where
    )

    /**
     * Create an aliased <code>public.act_id_tenant</code> table reference
     */
    constructor(alias: String) : this(DSL.name(alias))

    /**
     * Create an aliased <code>public.act_id_tenant</code> table reference
     */
    constructor(alias: Name) : this(alias, null)

    /**
     * Create a <code>public.act_id_tenant</code> table reference
     */
    constructor() : this(DSL.name("act_id_tenant"), null)

    constructor(
        path: Table<out Record>,
        childPath: ForeignKey<out Record, ActIdTenantRecord>?,
        parentPath: InverseForeignKey<out Record, ActIdTenantRecord>?
    ) : this(
        Internal.createPathAlias(path, childPath, parentPath),
        path,
        childPath,
        parentPath,
        ACT_ID_TENANT,
        null,
        null
    )

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class ActIdTenantPath : ActIdTenant, Path<ActIdTenantRecord> {
        constructor(
            path: Table<out Record>,
            childPath: ForeignKey<out Record, ActIdTenantRecord>?,
            parentPath: InverseForeignKey<out Record, ActIdTenantRecord>?
        ) : super(path, childPath, parentPath)

        private constructor(alias: Name, aliased: Table<ActIdTenantRecord>) : super(alias, aliased)

        override fun `as`(alias: String): ActIdTenantPath = ActIdTenantPath(DSL.name(alias), this)
        override fun `as`(alias: Name): ActIdTenantPath = ActIdTenantPath(alias, this)
        override fun `as`(alias: Table<*>): ActIdTenantPath = ActIdTenantPath(alias.qualifiedName, this)
    }

    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<ActIdTenantRecord> = ACT_ID_TENANT_PKEY

    private lateinit var _actIdTenantMember: ActIdTenantMemberPath

    /**
     * Get the implicit to-many join path to the
     * <code>public.act_id_tenant_member</code> table
     */
    fun actIdTenantMember(): ActIdTenantMemberPath {
        if (!this::_actIdTenantMember.isInitialized)
            _actIdTenantMember = ActIdTenantMemberPath(this, null, ACT_ID_TENANT_MEMBER__ACT_FK_TENANT_MEMB.inverseKey)

        return _actIdTenantMember
    }

    val actIdTenantMember: ActIdTenantMemberPath
        get(): ActIdTenantMemberPath = actIdTenantMember()

    /**
     * Get the implicit many-to-many join path to the
     * <code>public.act_id_group</code> table
     */
    val actIdGroup: ActIdGroupPath
        get(): ActIdGroupPath = actIdTenantMember().actIdGroup()

    /**
     * Get the implicit many-to-many join path to the
     * <code>public.act_id_user</code> table
     */
    val actIdUser: ActIdUserPath
        get(): ActIdUserPath = actIdTenantMember().actIdUser()

    override fun `as`(alias: String): ActIdTenant = ActIdTenant(DSL.name(alias), this)
    override fun `as`(alias: Name): ActIdTenant = ActIdTenant(alias, this)
    override fun `as`(alias: Table<*>): ActIdTenant = ActIdTenant(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): ActIdTenant = ActIdTenant(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): ActIdTenant = ActIdTenant(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): ActIdTenant = ActIdTenant(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): ActIdTenant =
        ActIdTenant(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): ActIdTenant = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): ActIdTenant = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): ActIdTenant = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(condition: SQL): ActIdTenant = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(@Stringly.SQL condition: String): ActIdTenant = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(@Stringly.SQL condition: String, vararg binds: Any?): ActIdTenant =
        where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): ActIdTenant =
        where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): ActIdTenant = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): ActIdTenant = where(DSL.notExists(select))
}
