/*
 * This file is generated by jOOQ.
 */
package emented.jooq.main.tables

import emented.jooq.main.Public
import emented.jooq.main.indexes.ACT_IDX_DEC_DEF_REQ_ID
import emented.jooq.main.indexes.ACT_IDX_DEC_DEF_TENANT_ID
import emented.jooq.main.keys.ACT_RE_DECISION_DEF_PKEY
import emented.jooq.main.keys.ACT_RE_DECISION_DEF__ACT_FK_DEC_REQ
import emented.jooq.main.tables.ActReDecisionReqDef.ActReDecisionReqDefPath
import emented.jooq.main.tables.records.ActReDecisionDefRecord
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl

/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ActReDecisionDef(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, ActReDecisionDefRecord>?,
    parentPath: InverseForeignKey<out Record, ActReDecisionDefRecord>?,
    aliased: Table<ActReDecisionDefRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
) : TableImpl<ActReDecisionDefRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.act_re_decision_def</code>
         */
        val ACT_RE_DECISION_DEF: ActReDecisionDef = ActReDecisionDef()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<ActReDecisionDefRecord> = ActReDecisionDefRecord::class.java

    /**
     * The column <code>public.act_re_decision_def.id_</code>.
     */
    val ID_: TableField<ActReDecisionDefRecord, String?> =
        createField(DSL.name("id_"), SQLDataType.VARCHAR(64).nullable(false), this, "")

    /**
     * The column <code>public.act_re_decision_def.rev_</code>.
     */
    val REV_: TableField<ActReDecisionDefRecord, Int?> = createField(DSL.name("rev_"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>public.act_re_decision_def.category_</code>.
     */
    val CATEGORY_: TableField<ActReDecisionDefRecord, String?> =
        createField(DSL.name("category_"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.act_re_decision_def.name_</code>.
     */
    val NAME_: TableField<ActReDecisionDefRecord, String?> =
        createField(DSL.name("name_"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.act_re_decision_def.key_</code>.
     */
    val KEY_: TableField<ActReDecisionDefRecord, String?> =
        createField(DSL.name("key_"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>public.act_re_decision_def.version_</code>.
     */
    val VERSION_: TableField<ActReDecisionDefRecord, Int?> =
        createField(DSL.name("version_"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.act_re_decision_def.deployment_id_</code>.
     */
    val DEPLOYMENT_ID_: TableField<ActReDecisionDefRecord, String?> =
        createField(DSL.name("deployment_id_"), SQLDataType.VARCHAR(64), this, "")

    /**
     * The column <code>public.act_re_decision_def.resource_name_</code>.
     */
    val RESOURCE_NAME_: TableField<ActReDecisionDefRecord, String?> =
        createField(DSL.name("resource_name_"), SQLDataType.VARCHAR(4000), this, "")

    /**
     * The column <code>public.act_re_decision_def.dgrm_resource_name_</code>.
     */
    val DGRM_RESOURCE_NAME_: TableField<ActReDecisionDefRecord, String?> =
        createField(DSL.name("dgrm_resource_name_"), SQLDataType.VARCHAR(4000), this, "")

    /**
     * The column <code>public.act_re_decision_def.dec_req_id_</code>.
     */
    val DEC_REQ_ID_: TableField<ActReDecisionDefRecord, String?> =
        createField(DSL.name("dec_req_id_"), SQLDataType.VARCHAR(64), this, "")

    /**
     * The column <code>public.act_re_decision_def.dec_req_key_</code>.
     */
    val DEC_REQ_KEY_: TableField<ActReDecisionDefRecord, String?> =
        createField(DSL.name("dec_req_key_"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.act_re_decision_def.tenant_id_</code>.
     */
    val TENANT_ID_: TableField<ActReDecisionDefRecord, String?> =
        createField(DSL.name("tenant_id_"), SQLDataType.VARCHAR(64), this, "")

    /**
     * The column <code>public.act_re_decision_def.history_ttl_</code>.
     */
    val HISTORY_TTL_: TableField<ActReDecisionDefRecord, Int?> =
        createField(DSL.name("history_ttl_"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>public.act_re_decision_def.version_tag_</code>.
     */
    val VERSION_TAG_: TableField<ActReDecisionDefRecord, String?> =
        createField(DSL.name("version_tag_"), SQLDataType.VARCHAR(64), this, "")

    private constructor(alias: Name, aliased: Table<ActReDecisionDefRecord>?) : this(
        alias,
        null,
        null,
        null,
        aliased,
        null,
        null
    )

    private constructor(alias: Name, aliased: Table<ActReDecisionDefRecord>?, parameters: Array<Field<*>?>?) : this(
        alias,
        null,
        null,
        null,
        aliased,
        parameters,
        null
    )

    private constructor(alias: Name, aliased: Table<ActReDecisionDefRecord>?, where: Condition?) : this(
        alias,
        null,
        null,
        null,
        aliased,
        null,
        where
    )

    /**
     * Create an aliased <code>public.act_re_decision_def</code> table reference
     */
    constructor(alias: String) : this(DSL.name(alias))

    /**
     * Create an aliased <code>public.act_re_decision_def</code> table reference
     */
    constructor(alias: Name) : this(alias, null)

    /**
     * Create a <code>public.act_re_decision_def</code> table reference
     */
    constructor() : this(DSL.name("act_re_decision_def"), null)

    constructor(
        path: Table<out Record>,
        childPath: ForeignKey<out Record, ActReDecisionDefRecord>?,
        parentPath: InverseForeignKey<out Record, ActReDecisionDefRecord>?
    ) : this(
        Internal.createPathAlias(path, childPath, parentPath),
        path,
        childPath,
        parentPath,
        ACT_RE_DECISION_DEF,
        null,
        null
    )

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class ActReDecisionDefPath : ActReDecisionDef, Path<ActReDecisionDefRecord> {
        constructor(
            path: Table<out Record>,
            childPath: ForeignKey<out Record, ActReDecisionDefRecord>?,
            parentPath: InverseForeignKey<out Record, ActReDecisionDefRecord>?
        ) : super(path, childPath, parentPath)

        private constructor(alias: Name, aliased: Table<ActReDecisionDefRecord>) : super(alias, aliased)

        override fun `as`(alias: String): ActReDecisionDefPath = ActReDecisionDefPath(DSL.name(alias), this)
        override fun `as`(alias: Name): ActReDecisionDefPath = ActReDecisionDefPath(alias, this)
        override fun `as`(alias: Table<*>): ActReDecisionDefPath = ActReDecisionDefPath(alias.qualifiedName, this)
    }

    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(ACT_IDX_DEC_DEF_REQ_ID, ACT_IDX_DEC_DEF_TENANT_ID)
    override fun getPrimaryKey(): UniqueKey<ActReDecisionDefRecord> = ACT_RE_DECISION_DEF_PKEY
    override fun getReferences(): List<ForeignKey<ActReDecisionDefRecord, *>> =
        listOf(ACT_RE_DECISION_DEF__ACT_FK_DEC_REQ)

    private lateinit var _actReDecisionReqDef: ActReDecisionReqDefPath

    /**
     * Get the implicit join path to the
     * <code>public.act_re_decision_req_def</code> table.
     */
    fun actReDecisionReqDef(): ActReDecisionReqDefPath {
        if (!this::_actReDecisionReqDef.isInitialized)
            _actReDecisionReqDef = ActReDecisionReqDefPath(this, ACT_RE_DECISION_DEF__ACT_FK_DEC_REQ, null)

        return _actReDecisionReqDef
    }

    val actReDecisionReqDef: ActReDecisionReqDefPath
        get(): ActReDecisionReqDefPath = actReDecisionReqDef()

    override fun `as`(alias: String): ActReDecisionDef = ActReDecisionDef(DSL.name(alias), this)
    override fun `as`(alias: Name): ActReDecisionDef = ActReDecisionDef(alias, this)
    override fun `as`(alias: Table<*>): ActReDecisionDef = ActReDecisionDef(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): ActReDecisionDef = ActReDecisionDef(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): ActReDecisionDef = ActReDecisionDef(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): ActReDecisionDef = ActReDecisionDef(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): ActReDecisionDef =
        ActReDecisionDef(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): ActReDecisionDef = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): ActReDecisionDef = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): ActReDecisionDef = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(condition: SQL): ActReDecisionDef = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(@Stringly.SQL condition: String): ActReDecisionDef = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(@Stringly.SQL condition: String, vararg binds: Any?): ActReDecisionDef =
        where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): ActReDecisionDef =
        where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): ActReDecisionDef = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): ActReDecisionDef = where(DSL.notExists(select))
}
