/*
 * This file is generated by jOOQ.
 */
package emented.jooq.main.tables

import emented.jooq.main.Public
import emented.jooq.main.indexes.ACT_IDX_CASE_DEF_TENANT_ID
import emented.jooq.main.keys.ACT_RE_CASE_DEF_PKEY
import emented.jooq.main.keys.ACT_RU_CASE_EXECUTION__ACT_FK_CASE_EXE_CASE_DEF
import emented.jooq.main.keys.ACT_RU_TASK__ACT_FK_TASK_CASE_DEF
import emented.jooq.main.tables.ActRuCaseExecution.ActRuCaseExecutionPath
import emented.jooq.main.tables.ActRuTask.ActRuTaskPath
import emented.jooq.main.tables.records.ActReCaseDefRecord
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl

/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ActReCaseDef(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, ActReCaseDefRecord>?,
    parentPath: InverseForeignKey<out Record, ActReCaseDefRecord>?,
    aliased: Table<ActReCaseDefRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
) : TableImpl<ActReCaseDefRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.act_re_case_def</code>
         */
        val ACT_RE_CASE_DEF: ActReCaseDef = ActReCaseDef()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<ActReCaseDefRecord> = ActReCaseDefRecord::class.java

    /**
     * The column <code>public.act_re_case_def.id_</code>.
     */
    val ID_: TableField<ActReCaseDefRecord, String?> =
        createField(DSL.name("id_"), SQLDataType.VARCHAR(64).nullable(false), this, "")

    /**
     * The column <code>public.act_re_case_def.rev_</code>.
     */
    val REV_: TableField<ActReCaseDefRecord, Int?> = createField(DSL.name("rev_"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>public.act_re_case_def.category_</code>.
     */
    val CATEGORY_: TableField<ActReCaseDefRecord, String?> =
        createField(DSL.name("category_"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.act_re_case_def.name_</code>.
     */
    val NAME_: TableField<ActReCaseDefRecord, String?> =
        createField(DSL.name("name_"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.act_re_case_def.key_</code>.
     */
    val KEY_: TableField<ActReCaseDefRecord, String?> =
        createField(DSL.name("key_"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>public.act_re_case_def.version_</code>.
     */
    val VERSION_: TableField<ActReCaseDefRecord, Int?> =
        createField(DSL.name("version_"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.act_re_case_def.deployment_id_</code>.
     */
    val DEPLOYMENT_ID_: TableField<ActReCaseDefRecord, String?> =
        createField(DSL.name("deployment_id_"), SQLDataType.VARCHAR(64), this, "")

    /**
     * The column <code>public.act_re_case_def.resource_name_</code>.
     */
    val RESOURCE_NAME_: TableField<ActReCaseDefRecord, String?> =
        createField(DSL.name("resource_name_"), SQLDataType.VARCHAR(4000), this, "")

    /**
     * The column <code>public.act_re_case_def.dgrm_resource_name_</code>.
     */
    val DGRM_RESOURCE_NAME_: TableField<ActReCaseDefRecord, String?> =
        createField(DSL.name("dgrm_resource_name_"), SQLDataType.VARCHAR(4000), this, "")

    /**
     * The column <code>public.act_re_case_def.tenant_id_</code>.
     */
    val TENANT_ID_: TableField<ActReCaseDefRecord, String?> =
        createField(DSL.name("tenant_id_"), SQLDataType.VARCHAR(64), this, "")

    /**
     * The column <code>public.act_re_case_def.history_ttl_</code>.
     */
    val HISTORY_TTL_: TableField<ActReCaseDefRecord, Int?> =
        createField(DSL.name("history_ttl_"), SQLDataType.INTEGER, this, "")

    private constructor(alias: Name, aliased: Table<ActReCaseDefRecord>?) : this(
        alias,
        null,
        null,
        null,
        aliased,
        null,
        null
    )

    private constructor(alias: Name, aliased: Table<ActReCaseDefRecord>?, parameters: Array<Field<*>?>?) : this(
        alias,
        null,
        null,
        null,
        aliased,
        parameters,
        null
    )

    private constructor(alias: Name, aliased: Table<ActReCaseDefRecord>?, where: Condition?) : this(
        alias,
        null,
        null,
        null,
        aliased,
        null,
        where
    )

    /**
     * Create an aliased <code>public.act_re_case_def</code> table reference
     */
    constructor(alias: String) : this(DSL.name(alias))

    /**
     * Create an aliased <code>public.act_re_case_def</code> table reference
     */
    constructor(alias: Name) : this(alias, null)

    /**
     * Create a <code>public.act_re_case_def</code> table reference
     */
    constructor() : this(DSL.name("act_re_case_def"), null)

    constructor(
        path: Table<out Record>,
        childPath: ForeignKey<out Record, ActReCaseDefRecord>?,
        parentPath: InverseForeignKey<out Record, ActReCaseDefRecord>?
    ) : this(
        Internal.createPathAlias(path, childPath, parentPath),
        path,
        childPath,
        parentPath,
        ACT_RE_CASE_DEF,
        null,
        null
    )

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class ActReCaseDefPath : ActReCaseDef, Path<ActReCaseDefRecord> {
        constructor(
            path: Table<out Record>,
            childPath: ForeignKey<out Record, ActReCaseDefRecord>?,
            parentPath: InverseForeignKey<out Record, ActReCaseDefRecord>?
        ) : super(path, childPath, parentPath)

        private constructor(alias: Name, aliased: Table<ActReCaseDefRecord>) : super(alias, aliased)

        override fun `as`(alias: String): ActReCaseDefPath = ActReCaseDefPath(DSL.name(alias), this)
        override fun `as`(alias: Name): ActReCaseDefPath = ActReCaseDefPath(alias, this)
        override fun `as`(alias: Table<*>): ActReCaseDefPath = ActReCaseDefPath(alias.qualifiedName, this)
    }

    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(ACT_IDX_CASE_DEF_TENANT_ID)
    override fun getPrimaryKey(): UniqueKey<ActReCaseDefRecord> = ACT_RE_CASE_DEF_PKEY

    private lateinit var _actRuCaseExecution: ActRuCaseExecutionPath

    /**
     * Get the implicit to-many join path to the
     * <code>public.act_ru_case_execution</code> table
     */
    fun actRuCaseExecution(): ActRuCaseExecutionPath {
        if (!this::_actRuCaseExecution.isInitialized)
            _actRuCaseExecution =
                ActRuCaseExecutionPath(this, null, ACT_RU_CASE_EXECUTION__ACT_FK_CASE_EXE_CASE_DEF.inverseKey)

        return _actRuCaseExecution
    }

    val actRuCaseExecution: ActRuCaseExecutionPath
        get(): ActRuCaseExecutionPath = actRuCaseExecution()

    private lateinit var _actRuTask: ActRuTaskPath

    /**
     * Get the implicit to-many join path to the <code>public.act_ru_task</code>
     * table
     */
    fun actRuTask(): ActRuTaskPath {
        if (!this::_actRuTask.isInitialized)
            _actRuTask = ActRuTaskPath(this, null, ACT_RU_TASK__ACT_FK_TASK_CASE_DEF.inverseKey)

        return _actRuTask
    }

    val actRuTask: ActRuTaskPath
        get(): ActRuTaskPath = actRuTask()

    override fun `as`(alias: String): ActReCaseDef = ActReCaseDef(DSL.name(alias), this)
    override fun `as`(alias: Name): ActReCaseDef = ActReCaseDef(alias, this)
    override fun `as`(alias: Table<*>): ActReCaseDef = ActReCaseDef(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): ActReCaseDef = ActReCaseDef(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): ActReCaseDef = ActReCaseDef(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): ActReCaseDef = ActReCaseDef(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): ActReCaseDef =
        ActReCaseDef(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): ActReCaseDef = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): ActReCaseDef = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): ActReCaseDef = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(condition: SQL): ActReCaseDef = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(@Stringly.SQL condition: String): ActReCaseDef = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(@Stringly.SQL condition: String, vararg binds: Any?): ActReCaseDef =
        where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): ActReCaseDef =
        where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): ActReCaseDef = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): ActReCaseDef = where(DSL.notExists(select))
}
