/*
 * This file is generated by jOOQ.
 */
package emented.jooq.main.tables

import emented.jooq.main.Public
import emented.jooq.main.indexes.ACT_IDX_EXT_TASK_ERR_DETAILS
import emented.jooq.main.indexes.ACT_IDX_EXT_TASK_EXEC
import emented.jooq.main.indexes.ACT_IDX_EXT_TASK_PRIORITY
import emented.jooq.main.indexes.ACT_IDX_EXT_TASK_TENANT_ID
import emented.jooq.main.indexes.ACT_IDX_EXT_TASK_TOPIC
import emented.jooq.main.keys.ACT_RU_EXT_TASK_PKEY
import emented.jooq.main.keys.ACT_RU_EXT_TASK__ACT_FK_EXT_TASK_ERROR_DETAILS
import emented.jooq.main.keys.ACT_RU_EXT_TASK__ACT_FK_EXT_TASK_EXE
import emented.jooq.main.tables.ActGeBytearray.ActGeBytearrayPath
import emented.jooq.main.tables.ActRuExecution.ActRuExecutionPath
import emented.jooq.main.tables.records.ActRuExtTaskRecord
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import java.time.LocalDateTime

/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ActRuExtTask(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, ActRuExtTaskRecord>?,
    parentPath: InverseForeignKey<out Record, ActRuExtTaskRecord>?,
    aliased: Table<ActRuExtTaskRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
) : TableImpl<ActRuExtTaskRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.act_ru_ext_task</code>
         */
        val ACT_RU_EXT_TASK: ActRuExtTask = ActRuExtTask()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<ActRuExtTaskRecord> = ActRuExtTaskRecord::class.java

    /**
     * The column <code>public.act_ru_ext_task.id_</code>.
     */
    val ID_: TableField<ActRuExtTaskRecord, String?> =
        createField(DSL.name("id_"), SQLDataType.VARCHAR(64).nullable(false), this, "")

    /**
     * The column <code>public.act_ru_ext_task.rev_</code>.
     */
    val REV_: TableField<ActRuExtTaskRecord, Int?> =
        createField(DSL.name("rev_"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.act_ru_ext_task.worker_id_</code>.
     */
    val WORKER_ID_: TableField<ActRuExtTaskRecord, String?> =
        createField(DSL.name("worker_id_"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.act_ru_ext_task.topic_name_</code>.
     */
    val TOPIC_NAME_: TableField<ActRuExtTaskRecord, String?> =
        createField(DSL.name("topic_name_"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.act_ru_ext_task.retries_</code>.
     */
    val RETRIES_: TableField<ActRuExtTaskRecord, Int?> =
        createField(DSL.name("retries_"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>public.act_ru_ext_task.error_msg_</code>.
     */
    val ERROR_MSG_: TableField<ActRuExtTaskRecord, String?> =
        createField(DSL.name("error_msg_"), SQLDataType.VARCHAR(4000), this, "")

    /**
     * The column <code>public.act_ru_ext_task.error_details_id_</code>.
     */
    val ERROR_DETAILS_ID_: TableField<ActRuExtTaskRecord, String?> =
        createField(DSL.name("error_details_id_"), SQLDataType.VARCHAR(64), this, "")

    /**
     * The column <code>public.act_ru_ext_task.lock_exp_time_</code>.
     */
    val LOCK_EXP_TIME_: TableField<ActRuExtTaskRecord, LocalDateTime?> =
        createField(DSL.name("lock_exp_time_"), SQLDataType.LOCALDATETIME(6), this, "")

    /**
     * The column <code>public.act_ru_ext_task.create_time_</code>.
     */
    val CREATE_TIME_: TableField<ActRuExtTaskRecord, LocalDateTime?> =
        createField(DSL.name("create_time_"), SQLDataType.LOCALDATETIME(6), this, "")

    /**
     * The column <code>public.act_ru_ext_task.suspension_state_</code>.
     */
    val SUSPENSION_STATE_: TableField<ActRuExtTaskRecord, Int?> =
        createField(DSL.name("suspension_state_"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>public.act_ru_ext_task.execution_id_</code>.
     */
    val EXECUTION_ID_: TableField<ActRuExtTaskRecord, String?> =
        createField(DSL.name("execution_id_"), SQLDataType.VARCHAR(64), this, "")

    /**
     * The column <code>public.act_ru_ext_task.proc_inst_id_</code>.
     */
    val PROC_INST_ID_: TableField<ActRuExtTaskRecord, String?> =
        createField(DSL.name("proc_inst_id_"), SQLDataType.VARCHAR(64), this, "")

    /**
     * The column <code>public.act_ru_ext_task.proc_def_id_</code>.
     */
    val PROC_DEF_ID_: TableField<ActRuExtTaskRecord, String?> =
        createField(DSL.name("proc_def_id_"), SQLDataType.VARCHAR(64), this, "")

    /**
     * The column <code>public.act_ru_ext_task.proc_def_key_</code>.
     */
    val PROC_DEF_KEY_: TableField<ActRuExtTaskRecord, String?> =
        createField(DSL.name("proc_def_key_"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.act_ru_ext_task.act_id_</code>.
     */
    val ACT_ID_: TableField<ActRuExtTaskRecord, String?> =
        createField(DSL.name("act_id_"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.act_ru_ext_task.act_inst_id_</code>.
     */
    val ACT_INST_ID_: TableField<ActRuExtTaskRecord, String?> =
        createField(DSL.name("act_inst_id_"), SQLDataType.VARCHAR(64), this, "")

    /**
     * The column <code>public.act_ru_ext_task.tenant_id_</code>.
     */
    val TENANT_ID_: TableField<ActRuExtTaskRecord, String?> =
        createField(DSL.name("tenant_id_"), SQLDataType.VARCHAR(64), this, "")

    /**
     * The column <code>public.act_ru_ext_task.priority_</code>.
     */
    val PRIORITY_: TableField<ActRuExtTaskRecord, Long?> = createField(
        DSL.name("priority_"),
        SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)),
        this,
        ""
    )

    /**
     * The column <code>public.act_ru_ext_task.last_failure_log_id_</code>.
     */
    val LAST_FAILURE_LOG_ID_: TableField<ActRuExtTaskRecord, String?> =
        createField(DSL.name("last_failure_log_id_"), SQLDataType.VARCHAR(64), this, "")

    private constructor(alias: Name, aliased: Table<ActRuExtTaskRecord>?) : this(
        alias,
        null,
        null,
        null,
        aliased,
        null,
        null
    )

    private constructor(alias: Name, aliased: Table<ActRuExtTaskRecord>?, parameters: Array<Field<*>?>?) : this(
        alias,
        null,
        null,
        null,
        aliased,
        parameters,
        null
    )

    private constructor(alias: Name, aliased: Table<ActRuExtTaskRecord>?, where: Condition?) : this(
        alias,
        null,
        null,
        null,
        aliased,
        null,
        where
    )

    /**
     * Create an aliased <code>public.act_ru_ext_task</code> table reference
     */
    constructor(alias: String) : this(DSL.name(alias))

    /**
     * Create an aliased <code>public.act_ru_ext_task</code> table reference
     */
    constructor(alias: Name) : this(alias, null)

    /**
     * Create a <code>public.act_ru_ext_task</code> table reference
     */
    constructor() : this(DSL.name("act_ru_ext_task"), null)

    constructor(
        path: Table<out Record>,
        childPath: ForeignKey<out Record, ActRuExtTaskRecord>?,
        parentPath: InverseForeignKey<out Record, ActRuExtTaskRecord>?
    ) : this(
        Internal.createPathAlias(path, childPath, parentPath),
        path,
        childPath,
        parentPath,
        ACT_RU_EXT_TASK,
        null,
        null
    )

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class ActRuExtTaskPath : ActRuExtTask, Path<ActRuExtTaskRecord> {
        constructor(
            path: Table<out Record>,
            childPath: ForeignKey<out Record, ActRuExtTaskRecord>?,
            parentPath: InverseForeignKey<out Record, ActRuExtTaskRecord>?
        ) : super(path, childPath, parentPath)

        private constructor(alias: Name, aliased: Table<ActRuExtTaskRecord>) : super(alias, aliased)

        override fun `as`(alias: String): ActRuExtTaskPath = ActRuExtTaskPath(DSL.name(alias), this)
        override fun `as`(alias: Name): ActRuExtTaskPath = ActRuExtTaskPath(alias, this)
        override fun `as`(alias: Table<*>): ActRuExtTaskPath = ActRuExtTaskPath(alias.qualifiedName, this)
    }

    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(
        ACT_IDX_EXT_TASK_ERR_DETAILS,
        ACT_IDX_EXT_TASK_EXEC,
        ACT_IDX_EXT_TASK_PRIORITY,
        ACT_IDX_EXT_TASK_TENANT_ID,
        ACT_IDX_EXT_TASK_TOPIC
    )

    override fun getPrimaryKey(): UniqueKey<ActRuExtTaskRecord> = ACT_RU_EXT_TASK_PKEY
    override fun getReferences(): List<ForeignKey<ActRuExtTaskRecord, *>> =
        listOf(ACT_RU_EXT_TASK__ACT_FK_EXT_TASK_ERROR_DETAILS, ACT_RU_EXT_TASK__ACT_FK_EXT_TASK_EXE)

    private lateinit var _actGeBytearray: ActGeBytearrayPath

    /**
     * Get the implicit join path to the <code>public.act_ge_bytearray</code>
     * table.
     */
    fun actGeBytearray(): ActGeBytearrayPath {
        if (!this::_actGeBytearray.isInitialized)
            _actGeBytearray = ActGeBytearrayPath(this, ACT_RU_EXT_TASK__ACT_FK_EXT_TASK_ERROR_DETAILS, null)

        return _actGeBytearray
    }

    val actGeBytearray: ActGeBytearrayPath
        get(): ActGeBytearrayPath = actGeBytearray()

    private lateinit var _actRuExecution: ActRuExecutionPath

    /**
     * Get the implicit join path to the <code>public.act_ru_execution</code>
     * table.
     */
    fun actRuExecution(): ActRuExecutionPath {
        if (!this::_actRuExecution.isInitialized)
            _actRuExecution = ActRuExecutionPath(this, ACT_RU_EXT_TASK__ACT_FK_EXT_TASK_EXE, null)

        return _actRuExecution
    }

    val actRuExecution: ActRuExecutionPath
        get(): ActRuExecutionPath = actRuExecution()

    override fun `as`(alias: String): ActRuExtTask = ActRuExtTask(DSL.name(alias), this)
    override fun `as`(alias: Name): ActRuExtTask = ActRuExtTask(alias, this)
    override fun `as`(alias: Table<*>): ActRuExtTask = ActRuExtTask(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): ActRuExtTask = ActRuExtTask(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): ActRuExtTask = ActRuExtTask(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): ActRuExtTask = ActRuExtTask(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): ActRuExtTask =
        ActRuExtTask(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): ActRuExtTask = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): ActRuExtTask = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): ActRuExtTask = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(condition: SQL): ActRuExtTask = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(@Stringly.SQL condition: String): ActRuExtTask = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(@Stringly.SQL condition: String, vararg binds: Any?): ActRuExtTask =
        where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): ActRuExtTask =
        where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): ActRuExtTask = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): ActRuExtTask = where(DSL.notExists(select))
}
