/*
 * This file is generated by jOOQ.
 */
package emented.jooq.main.tables

import emented.jooq.main.Public
import emented.jooq.main.indexes.ACT_IDX_ATHRZ_PROCEDEF
import emented.jooq.main.indexes.ACT_IDX_IDENT_LNK_GROUP
import emented.jooq.main.indexes.ACT_IDX_IDENT_LNK_USER
import emented.jooq.main.indexes.ACT_IDX_TSKASS_TASK
import emented.jooq.main.keys.ACT_RU_IDENTITYLINK_PKEY
import emented.jooq.main.keys.ACT_RU_IDENTITYLINK__ACT_FK_ATHRZ_PROCEDEF
import emented.jooq.main.keys.ACT_RU_IDENTITYLINK__ACT_FK_TSKASS_TASK
import emented.jooq.main.tables.ActReProcdef.ActReProcdefPath
import emented.jooq.main.tables.ActRuTask.ActRuTaskPath
import emented.jooq.main.tables.records.ActRuIdentitylinkRecord
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl

/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ActRuIdentitylink(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, ActRuIdentitylinkRecord>?,
    parentPath: InverseForeignKey<out Record, ActRuIdentitylinkRecord>?,
    aliased: Table<ActRuIdentitylinkRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
) : TableImpl<ActRuIdentitylinkRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.act_ru_identitylink</code>
         */
        val ACT_RU_IDENTITYLINK: ActRuIdentitylink = ActRuIdentitylink()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<ActRuIdentitylinkRecord> = ActRuIdentitylinkRecord::class.java

    /**
     * The column <code>public.act_ru_identitylink.id_</code>.
     */
    val ID_: TableField<ActRuIdentitylinkRecord, String?> =
        createField(DSL.name("id_"), SQLDataType.VARCHAR(64).nullable(false), this, "")

    /**
     * The column <code>public.act_ru_identitylink.rev_</code>.
     */
    val REV_: TableField<ActRuIdentitylinkRecord, Int?> = createField(DSL.name("rev_"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>public.act_ru_identitylink.group_id_</code>.
     */
    val GROUP_ID_: TableField<ActRuIdentitylinkRecord, String?> =
        createField(DSL.name("group_id_"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.act_ru_identitylink.type_</code>.
     */
    val TYPE_: TableField<ActRuIdentitylinkRecord, String?> =
        createField(DSL.name("type_"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.act_ru_identitylink.user_id_</code>.
     */
    val USER_ID_: TableField<ActRuIdentitylinkRecord, String?> =
        createField(DSL.name("user_id_"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.act_ru_identitylink.task_id_</code>.
     */
    val TASK_ID_: TableField<ActRuIdentitylinkRecord, String?> =
        createField(DSL.name("task_id_"), SQLDataType.VARCHAR(64), this, "")

    /**
     * The column <code>public.act_ru_identitylink.proc_def_id_</code>.
     */
    val PROC_DEF_ID_: TableField<ActRuIdentitylinkRecord, String?> =
        createField(DSL.name("proc_def_id_"), SQLDataType.VARCHAR(64), this, "")

    /**
     * The column <code>public.act_ru_identitylink.tenant_id_</code>.
     */
    val TENANT_ID_: TableField<ActRuIdentitylinkRecord, String?> =
        createField(DSL.name("tenant_id_"), SQLDataType.VARCHAR(64), this, "")

    private constructor(alias: Name, aliased: Table<ActRuIdentitylinkRecord>?) : this(
        alias,
        null,
        null,
        null,
        aliased,
        null,
        null
    )

    private constructor(alias: Name, aliased: Table<ActRuIdentitylinkRecord>?, parameters: Array<Field<*>?>?) : this(
        alias,
        null,
        null,
        null,
        aliased,
        parameters,
        null
    )

    private constructor(alias: Name, aliased: Table<ActRuIdentitylinkRecord>?, where: Condition?) : this(
        alias,
        null,
        null,
        null,
        aliased,
        null,
        where
    )

    /**
     * Create an aliased <code>public.act_ru_identitylink</code> table reference
     */
    constructor(alias: String) : this(DSL.name(alias))

    /**
     * Create an aliased <code>public.act_ru_identitylink</code> table reference
     */
    constructor(alias: Name) : this(alias, null)

    /**
     * Create a <code>public.act_ru_identitylink</code> table reference
     */
    constructor() : this(DSL.name("act_ru_identitylink"), null)

    constructor(
        path: Table<out Record>,
        childPath: ForeignKey<out Record, ActRuIdentitylinkRecord>?,
        parentPath: InverseForeignKey<out Record, ActRuIdentitylinkRecord>?
    ) : this(
        Internal.createPathAlias(path, childPath, parentPath),
        path,
        childPath,
        parentPath,
        ACT_RU_IDENTITYLINK,
        null,
        null
    )

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class ActRuIdentitylinkPath : ActRuIdentitylink, Path<ActRuIdentitylinkRecord> {
        constructor(
            path: Table<out Record>,
            childPath: ForeignKey<out Record, ActRuIdentitylinkRecord>?,
            parentPath: InverseForeignKey<out Record, ActRuIdentitylinkRecord>?
        ) : super(path, childPath, parentPath)

        private constructor(alias: Name, aliased: Table<ActRuIdentitylinkRecord>) : super(alias, aliased)

        override fun `as`(alias: String): ActRuIdentitylinkPath = ActRuIdentitylinkPath(DSL.name(alias), this)
        override fun `as`(alias: Name): ActRuIdentitylinkPath = ActRuIdentitylinkPath(alias, this)
        override fun `as`(alias: Table<*>): ActRuIdentitylinkPath = ActRuIdentitylinkPath(alias.qualifiedName, this)
    }

    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> =
        listOf(ACT_IDX_ATHRZ_PROCEDEF, ACT_IDX_IDENT_LNK_GROUP, ACT_IDX_IDENT_LNK_USER, ACT_IDX_TSKASS_TASK)

    override fun getPrimaryKey(): UniqueKey<ActRuIdentitylinkRecord> = ACT_RU_IDENTITYLINK_PKEY
    override fun getReferences(): List<ForeignKey<ActRuIdentitylinkRecord, *>> =
        listOf(ACT_RU_IDENTITYLINK__ACT_FK_TSKASS_TASK, ACT_RU_IDENTITYLINK__ACT_FK_ATHRZ_PROCEDEF)

    private lateinit var _actRuTask: ActRuTaskPath

    /**
     * Get the implicit join path to the <code>public.act_ru_task</code> table.
     */
    fun actRuTask(): ActRuTaskPath {
        if (!this::_actRuTask.isInitialized)
            _actRuTask = ActRuTaskPath(this, ACT_RU_IDENTITYLINK__ACT_FK_TSKASS_TASK, null)

        return _actRuTask
    }

    val actRuTask: ActRuTaskPath
        get(): ActRuTaskPath = actRuTask()

    private lateinit var _actReProcdef: ActReProcdefPath

    /**
     * Get the implicit join path to the <code>public.act_re_procdef</code>
     * table.
     */
    fun actReProcdef(): ActReProcdefPath {
        if (!this::_actReProcdef.isInitialized)
            _actReProcdef = ActReProcdefPath(this, ACT_RU_IDENTITYLINK__ACT_FK_ATHRZ_PROCEDEF, null)

        return _actReProcdef
    }

    val actReProcdef: ActReProcdefPath
        get(): ActReProcdefPath = actReProcdef()

    override fun `as`(alias: String): ActRuIdentitylink = ActRuIdentitylink(DSL.name(alias), this)
    override fun `as`(alias: Name): ActRuIdentitylink = ActRuIdentitylink(alias, this)
    override fun `as`(alias: Table<*>): ActRuIdentitylink = ActRuIdentitylink(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): ActRuIdentitylink = ActRuIdentitylink(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): ActRuIdentitylink = ActRuIdentitylink(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): ActRuIdentitylink = ActRuIdentitylink(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): ActRuIdentitylink =
        ActRuIdentitylink(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): ActRuIdentitylink = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): ActRuIdentitylink = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): ActRuIdentitylink = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(condition: SQL): ActRuIdentitylink = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(@Stringly.SQL condition: String): ActRuIdentitylink = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(@Stringly.SQL condition: String, vararg binds: Any?): ActRuIdentitylink =
        where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): ActRuIdentitylink =
        where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): ActRuIdentitylink = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): ActRuIdentitylink = where(DSL.notExists(select))
}
