/*
 * This file is generated by jOOQ.
 */
package emented.jooq.main.tables

import emented.jooq.main.Public
import emented.jooq.main.indexes.ACT_IDX_TASK_METER_LOG_TIME
import emented.jooq.main.keys.ACT_RU_TASK_METER_LOG_PKEY
import emented.jooq.main.tables.records.ActRuTaskMeterLogRecord
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import java.time.LocalDateTime

/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ActRuTaskMeterLog(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, ActRuTaskMeterLogRecord>?,
    parentPath: InverseForeignKey<out Record, ActRuTaskMeterLogRecord>?,
    aliased: Table<ActRuTaskMeterLogRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
) : TableImpl<ActRuTaskMeterLogRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.act_ru_task_meter_log</code>
         */
        val ACT_RU_TASK_METER_LOG: ActRuTaskMeterLog = ActRuTaskMeterLog()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<ActRuTaskMeterLogRecord> = ActRuTaskMeterLogRecord::class.java

    /**
     * The column <code>public.act_ru_task_meter_log.id_</code>.
     */
    val ID_: TableField<ActRuTaskMeterLogRecord, String?> =
        createField(DSL.name("id_"), SQLDataType.VARCHAR(64).nullable(false), this, "")

    /**
     * The column <code>public.act_ru_task_meter_log.assignee_hash_</code>.
     */
    val ASSIGNEE_HASH_: TableField<ActRuTaskMeterLogRecord, Long?> =
        createField(DSL.name("assignee_hash_"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>public.act_ru_task_meter_log.timestamp_</code>.
     */
    val TIMESTAMP_: TableField<ActRuTaskMeterLogRecord, LocalDateTime?> =
        createField(DSL.name("timestamp_"), SQLDataType.LOCALDATETIME(6), this, "")

    private constructor(alias: Name, aliased: Table<ActRuTaskMeterLogRecord>?) : this(
        alias,
        null,
        null,
        null,
        aliased,
        null,
        null
    )

    private constructor(alias: Name, aliased: Table<ActRuTaskMeterLogRecord>?, parameters: Array<Field<*>?>?) : this(
        alias,
        null,
        null,
        null,
        aliased,
        parameters,
        null
    )

    private constructor(alias: Name, aliased: Table<ActRuTaskMeterLogRecord>?, where: Condition?) : this(
        alias,
        null,
        null,
        null,
        aliased,
        null,
        where
    )

    /**
     * Create an aliased <code>public.act_ru_task_meter_log</code> table
     * reference
     */
    constructor(alias: String) : this(DSL.name(alias))

    /**
     * Create an aliased <code>public.act_ru_task_meter_log</code> table
     * reference
     */
    constructor(alias: Name) : this(alias, null)

    /**
     * Create a <code>public.act_ru_task_meter_log</code> table reference
     */
    constructor() : this(DSL.name("act_ru_task_meter_log"), null)

    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(ACT_IDX_TASK_METER_LOG_TIME)
    override fun getPrimaryKey(): UniqueKey<ActRuTaskMeterLogRecord> = ACT_RU_TASK_METER_LOG_PKEY
    override fun `as`(alias: String): ActRuTaskMeterLog = ActRuTaskMeterLog(DSL.name(alias), this)
    override fun `as`(alias: Name): ActRuTaskMeterLog = ActRuTaskMeterLog(alias, this)
    override fun `as`(alias: Table<*>): ActRuTaskMeterLog = ActRuTaskMeterLog(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): ActRuTaskMeterLog = ActRuTaskMeterLog(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): ActRuTaskMeterLog = ActRuTaskMeterLog(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): ActRuTaskMeterLog = ActRuTaskMeterLog(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): ActRuTaskMeterLog =
        ActRuTaskMeterLog(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): ActRuTaskMeterLog = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): ActRuTaskMeterLog = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): ActRuTaskMeterLog = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(condition: SQL): ActRuTaskMeterLog = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(@Stringly.SQL condition: String): ActRuTaskMeterLog = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(@Stringly.SQL condition: String, vararg binds: Any?): ActRuTaskMeterLog =
        where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): ActRuTaskMeterLog =
        where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): ActRuTaskMeterLog = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): ActRuTaskMeterLog = where(DSL.notExists(select))
}
