/*
 * This file is generated by jOOQ.
 */
package emented.jooq.main.tables


import emented.jooq.main.Public
import emented.jooq.main.indexes.IDX_QRTZ_J_GRP
import emented.jooq.main.indexes.IDX_QRTZ_J_REQ_RECOVERY
import emented.jooq.main.keys.QRTZ_JOB_DETAILS_PKEY
import emented.jooq.main.keys.QRTZ_TRIGGERS__QRTZ_TRIGGERS_SCHED_NAME_JOB_NAME_JOB_GROUP_FKEY
import emented.jooq.main.tables.QrtzTriggers.QrtzTriggersPath
import emented.jooq.main.tables.records.QrtzJobDetailsRecord

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class QrtzJobDetails(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, QrtzJobDetailsRecord>?,
    parentPath: InverseForeignKey<out Record, QrtzJobDetailsRecord>?,
    aliased: Table<QrtzJobDetailsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<QrtzJobDetailsRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.qrtz_job_details</code>
         */
        val QRTZ_JOB_DETAILS: QrtzJobDetails = QrtzJobDetails()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<QrtzJobDetailsRecord> = QrtzJobDetailsRecord::class.java

    /**
     * The column <code>public.qrtz_job_details.sched_name</code>.
     */
    val SCHED_NAME: TableField<QrtzJobDetailsRecord, String?> = createField(DSL.name("sched_name"), SQLDataType.VARCHAR(120).nullable(false), this, "")

    /**
     * The column <code>public.qrtz_job_details.job_name</code>.
     */
    val JOB_NAME: TableField<QrtzJobDetailsRecord, String?> = createField(DSL.name("job_name"), SQLDataType.VARCHAR(200).nullable(false), this, "")

    /**
     * The column <code>public.qrtz_job_details.job_group</code>.
     */
    val JOB_GROUP: TableField<QrtzJobDetailsRecord, String?> = createField(DSL.name("job_group"), SQLDataType.VARCHAR(200).nullable(false), this, "")

    /**
     * The column <code>public.qrtz_job_details.description</code>.
     */
    val DESCRIPTION: TableField<QrtzJobDetailsRecord, String?> = createField(DSL.name("description"), SQLDataType.VARCHAR(250), this, "")

    /**
     * The column <code>public.qrtz_job_details.job_class_name</code>.
     */
    val JOB_CLASS_NAME: TableField<QrtzJobDetailsRecord, String?> = createField(DSL.name("job_class_name"), SQLDataType.VARCHAR(250).nullable(false), this, "")

    /**
     * The column <code>public.qrtz_job_details.is_durable</code>.
     */
    val IS_DURABLE: TableField<QrtzJobDetailsRecord, Boolean?> = createField(DSL.name("is_durable"), SQLDataType.BOOLEAN.nullable(false), this, "")

    /**
     * The column <code>public.qrtz_job_details.is_nonconcurrent</code>.
     */
    val IS_NONCONCURRENT: TableField<QrtzJobDetailsRecord, Boolean?> = createField(DSL.name("is_nonconcurrent"), SQLDataType.BOOLEAN.nullable(false), this, "")

    /**
     * The column <code>public.qrtz_job_details.is_update_data</code>.
     */
    val IS_UPDATE_DATA: TableField<QrtzJobDetailsRecord, Boolean?> = createField(DSL.name("is_update_data"), SQLDataType.BOOLEAN.nullable(false), this, "")

    /**
     * The column <code>public.qrtz_job_details.requests_recovery</code>.
     */
    val REQUESTS_RECOVERY: TableField<QrtzJobDetailsRecord, Boolean?> = createField(DSL.name("requests_recovery"), SQLDataType.BOOLEAN.nullable(false), this, "")

    /**
     * The column <code>public.qrtz_job_details.job_data</code>.
     */
    val JOB_DATA: TableField<QrtzJobDetailsRecord, ByteArray?> = createField(DSL.name("job_data"), SQLDataType.BLOB, this, "")

    private constructor(alias: Name, aliased: Table<QrtzJobDetailsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<QrtzJobDetailsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<QrtzJobDetailsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.qrtz_job_details</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.qrtz_job_details</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.qrtz_job_details</code> table reference
     */
    constructor(): this(DSL.name("qrtz_job_details"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, QrtzJobDetailsRecord>?, parentPath: InverseForeignKey<out Record, QrtzJobDetailsRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, QRTZ_JOB_DETAILS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class QrtzJobDetailsPath : QrtzJobDetails, Path<QrtzJobDetailsRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, QrtzJobDetailsRecord>?, parentPath: InverseForeignKey<out Record, QrtzJobDetailsRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<QrtzJobDetailsRecord>): super(alias, aliased)
        override fun `as`(alias: String): QrtzJobDetailsPath = QrtzJobDetailsPath(DSL.name(alias), this)
        override fun `as`(alias: Name): QrtzJobDetailsPath = QrtzJobDetailsPath(alias, this)
        override fun `as`(alias: Table<*>): QrtzJobDetailsPath = QrtzJobDetailsPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(IDX_QRTZ_J_GRP, IDX_QRTZ_J_REQ_RECOVERY)
    override fun getPrimaryKey(): UniqueKey<QrtzJobDetailsRecord> = QRTZ_JOB_DETAILS_PKEY

    private lateinit var _qrtzTriggers: QrtzTriggersPath

    /**
     * Get the implicit to-many join path to the
     * <code>public.qrtz_triggers</code> table
     */
    fun qrtzTriggers(): QrtzTriggersPath {
        if (!this::_qrtzTriggers.isInitialized)
            _qrtzTriggers = QrtzTriggersPath(this, null, QRTZ_TRIGGERS__QRTZ_TRIGGERS_SCHED_NAME_JOB_NAME_JOB_GROUP_FKEY.inverseKey)

        return _qrtzTriggers;
    }

    val qrtzTriggers: QrtzTriggersPath
        get(): QrtzTriggersPath = qrtzTriggers()
    override fun `as`(alias: String): QrtzJobDetails = QrtzJobDetails(DSL.name(alias), this)
    override fun `as`(alias: Name): QrtzJobDetails = QrtzJobDetails(alias, this)
    override fun `as`(alias: Table<*>): QrtzJobDetails = QrtzJobDetails(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): QrtzJobDetails = QrtzJobDetails(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): QrtzJobDetails = QrtzJobDetails(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): QrtzJobDetails = QrtzJobDetails(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): QrtzJobDetails = QrtzJobDetails(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): QrtzJobDetails = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): QrtzJobDetails = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): QrtzJobDetails = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): QrtzJobDetails = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): QrtzJobDetails = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): QrtzJobDetails = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): QrtzJobDetails = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): QrtzJobDetails = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): QrtzJobDetails = where(DSL.notExists(select))
}
