/*
 * This file is generated by jOOQ.
 */
package emented.jooq.main.tables


import emented.jooq.main.Public
import emented.jooq.main.keys.QRTZ_SIMPLE_TRIGGERS_PKEY
import emented.jooq.main.keys.QRTZ_SIMPLE_TRIGGERS__QRTZ_SIMPLE_TRIGGERS_SCHED_NAME_TRIGGER_NAME_TRIGGER_GROUP_FKEY
import emented.jooq.main.tables.QrtzTriggers.QrtzTriggersPath
import emented.jooq.main.tables.records.QrtzSimpleTriggersRecord

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class QrtzSimpleTriggers(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, QrtzSimpleTriggersRecord>?,
    parentPath: InverseForeignKey<out Record, QrtzSimpleTriggersRecord>?,
    aliased: Table<QrtzSimpleTriggersRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<QrtzSimpleTriggersRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.qrtz_simple_triggers</code>
         */
        val QRTZ_SIMPLE_TRIGGERS: QrtzSimpleTriggers = QrtzSimpleTriggers()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<QrtzSimpleTriggersRecord> = QrtzSimpleTriggersRecord::class.java

    /**
     * The column <code>public.qrtz_simple_triggers.sched_name</code>.
     */
    val SCHED_NAME: TableField<QrtzSimpleTriggersRecord, String?> = createField(DSL.name("sched_name"), SQLDataType.VARCHAR(120).nullable(false), this, "")

    /**
     * The column <code>public.qrtz_simple_triggers.trigger_name</code>.
     */
    val TRIGGER_NAME: TableField<QrtzSimpleTriggersRecord, String?> = createField(DSL.name("trigger_name"), SQLDataType.VARCHAR(200).nullable(false), this, "")

    /**
     * The column <code>public.qrtz_simple_triggers.trigger_group</code>.
     */
    val TRIGGER_GROUP: TableField<QrtzSimpleTriggersRecord, String?> = createField(DSL.name("trigger_group"), SQLDataType.VARCHAR(200).nullable(false), this, "")

    /**
     * The column <code>public.qrtz_simple_triggers.repeat_count</code>.
     */
    val REPEAT_COUNT: TableField<QrtzSimpleTriggersRecord, Long?> = createField(DSL.name("repeat_count"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.qrtz_simple_triggers.repeat_interval</code>.
     */
    val REPEAT_INTERVAL: TableField<QrtzSimpleTriggersRecord, Long?> = createField(DSL.name("repeat_interval"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.qrtz_simple_triggers.times_triggered</code>.
     */
    val TIMES_TRIGGERED: TableField<QrtzSimpleTriggersRecord, Long?> = createField(DSL.name("times_triggered"), SQLDataType.BIGINT.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<QrtzSimpleTriggersRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<QrtzSimpleTriggersRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<QrtzSimpleTriggersRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.qrtz_simple_triggers</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.qrtz_simple_triggers</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.qrtz_simple_triggers</code> table reference
     */
    constructor(): this(DSL.name("qrtz_simple_triggers"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, QrtzSimpleTriggersRecord>?, parentPath: InverseForeignKey<out Record, QrtzSimpleTriggersRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, QRTZ_SIMPLE_TRIGGERS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class QrtzSimpleTriggersPath : QrtzSimpleTriggers, Path<QrtzSimpleTriggersRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, QrtzSimpleTriggersRecord>?, parentPath: InverseForeignKey<out Record, QrtzSimpleTriggersRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<QrtzSimpleTriggersRecord>): super(alias, aliased)
        override fun `as`(alias: String): QrtzSimpleTriggersPath = QrtzSimpleTriggersPath(DSL.name(alias), this)
        override fun `as`(alias: Name): QrtzSimpleTriggersPath = QrtzSimpleTriggersPath(alias, this)
        override fun `as`(alias: Table<*>): QrtzSimpleTriggersPath = QrtzSimpleTriggersPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<QrtzSimpleTriggersRecord> = QRTZ_SIMPLE_TRIGGERS_PKEY
    override fun getReferences(): List<ForeignKey<QrtzSimpleTriggersRecord, *>> = listOf(QRTZ_SIMPLE_TRIGGERS__QRTZ_SIMPLE_TRIGGERS_SCHED_NAME_TRIGGER_NAME_TRIGGER_GROUP_FKEY)

    private lateinit var _qrtzTriggers: QrtzTriggersPath

    /**
     * Get the implicit join path to the <code>public.qrtz_triggers</code>
     * table.
     */
    fun qrtzTriggers(): QrtzTriggersPath {
        if (!this::_qrtzTriggers.isInitialized)
            _qrtzTriggers = QrtzTriggersPath(this, QRTZ_SIMPLE_TRIGGERS__QRTZ_SIMPLE_TRIGGERS_SCHED_NAME_TRIGGER_NAME_TRIGGER_GROUP_FKEY, null)

        return _qrtzTriggers;
    }

    val qrtzTriggers: QrtzTriggersPath
        get(): QrtzTriggersPath = qrtzTriggers()
    override fun `as`(alias: String): QrtzSimpleTriggers = QrtzSimpleTriggers(DSL.name(alias), this)
    override fun `as`(alias: Name): QrtzSimpleTriggers = QrtzSimpleTriggers(alias, this)
    override fun `as`(alias: Table<*>): QrtzSimpleTriggers = QrtzSimpleTriggers(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): QrtzSimpleTriggers = QrtzSimpleTriggers(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): QrtzSimpleTriggers = QrtzSimpleTriggers(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): QrtzSimpleTriggers = QrtzSimpleTriggers(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): QrtzSimpleTriggers = QrtzSimpleTriggers(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): QrtzSimpleTriggers = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): QrtzSimpleTriggers = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): QrtzSimpleTriggers = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): QrtzSimpleTriggers = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): QrtzSimpleTriggers = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): QrtzSimpleTriggers = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): QrtzSimpleTriggers = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): QrtzSimpleTriggers = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): QrtzSimpleTriggers = where(DSL.notExists(select))
}
