/*
 * This file is generated by jOOQ.
 */
package emented.jooq.main.tables

import emented.jooq.main.Public
import emented.jooq.main.keys.QRTZ_LOCKS_PKEY
import emented.jooq.main.tables.records.QrtzLocksRecord
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl

/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class QrtzLocks(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, QrtzLocksRecord>?,
    parentPath: InverseForeignKey<out Record, QrtzLocksRecord>?,
    aliased: Table<QrtzLocksRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
) : TableImpl<QrtzLocksRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.qrtz_locks</code>
         */
        val QRTZ_LOCKS: QrtzLocks = QrtzLocks()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<QrtzLocksRecord> = QrtzLocksRecord::class.java

    /**
     * The column <code>public.qrtz_locks.sched_name</code>.
     */
    val SCHED_NAME: TableField<QrtzLocksRecord, String?> =
        createField(DSL.name("sched_name"), SQLDataType.VARCHAR(120).nullable(false), this, "")

    /**
     * The column <code>public.qrtz_locks.lock_name</code>.
     */
    val LOCK_NAME: TableField<QrtzLocksRecord, String?> =
        createField(DSL.name("lock_name"), SQLDataType.VARCHAR(40).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<QrtzLocksRecord>?) : this(
        alias,
        null,
        null,
        null,
        aliased,
        null,
        null
    )

    private constructor(alias: Name, aliased: Table<QrtzLocksRecord>?, parameters: Array<Field<*>?>?) : this(
        alias,
        null,
        null,
        null,
        aliased,
        parameters,
        null
    )

    private constructor(alias: Name, aliased: Table<QrtzLocksRecord>?, where: Condition?) : this(
        alias,
        null,
        null,
        null,
        aliased,
        null,
        where
    )

    /**
     * Create an aliased <code>public.qrtz_locks</code> table reference
     */
    constructor(alias: String) : this(DSL.name(alias))

    /**
     * Create an aliased <code>public.qrtz_locks</code> table reference
     */
    constructor(alias: Name) : this(alias, null)

    /**
     * Create a <code>public.qrtz_locks</code> table reference
     */
    constructor() : this(DSL.name("qrtz_locks"), null)

    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<QrtzLocksRecord> = QRTZ_LOCKS_PKEY
    override fun `as`(alias: String): QrtzLocks = QrtzLocks(DSL.name(alias), this)
    override fun `as`(alias: Name): QrtzLocks = QrtzLocks(alias, this)
    override fun `as`(alias: Table<*>): QrtzLocks = QrtzLocks(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): QrtzLocks = QrtzLocks(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): QrtzLocks = QrtzLocks(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): QrtzLocks = QrtzLocks(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): QrtzLocks =
        QrtzLocks(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): QrtzLocks = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): QrtzLocks = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): QrtzLocks = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(condition: SQL): QrtzLocks = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(@Stringly.SQL condition: String): QrtzLocks = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(@Stringly.SQL condition: String, vararg binds: Any?): QrtzLocks =
        where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL
    override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): QrtzLocks =
        where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): QrtzLocks = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): QrtzLocks = where(DSL.notExists(select))
}
