/*
 * This file is generated by jOOQ.
 */
package emented.jooq.main.tables.references


import emented.jooq.main.tables.Category
import emented.jooq.main.tables.Comment
import emented.jooq.main.tables.Community
import emented.jooq.main.tables.CommunityEvent
import emented.jooq.main.tables.QrtzBlobTriggers
import emented.jooq.main.tables.QrtzCalendars
import emented.jooq.main.tables.QrtzCronTriggers
import emented.jooq.main.tables.QrtzFiredTriggers
import emented.jooq.main.tables.QrtzJobDetails
import emented.jooq.main.tables.QrtzLocks
import emented.jooq.main.tables.QrtzPausedTriggerGrps
import emented.jooq.main.tables.QrtzSchedulerState
import emented.jooq.main.tables.QrtzSimpleTriggers
import emented.jooq.main.tables.QrtzSimpropTriggers
import emented.jooq.main.tables.QrtzTriggers
import emented.jooq.main.tables.Role
import emented.jooq.main.tables.RoleUserRelation
import emented.jooq.main.tables.User



/**
 * The table <code>public.category</code>.
 */
val CATEGORY: Category = Category.CATEGORY

/**
 * The table <code>public.comment</code>.
 */
val COMMENT: Comment = Comment.COMMENT

/**
 * The table <code>public.community</code>.
 */
val COMMUNITY: Community = Community.COMMUNITY

/**
 * The table <code>public.community_event</code>.
 */
val COMMUNITY_EVENT: CommunityEvent = CommunityEvent.COMMUNITY_EVENT

/**
 * The table <code>public.qrtz_blob_triggers</code>.
 */
val QRTZ_BLOB_TRIGGERS: QrtzBlobTriggers = QrtzBlobTriggers.QRTZ_BLOB_TRIGGERS

/**
 * The table <code>public.qrtz_calendars</code>.
 */
val QRTZ_CALENDARS: QrtzCalendars = QrtzCalendars.QRTZ_CALENDARS

/**
 * The table <code>public.qrtz_cron_triggers</code>.
 */
val QRTZ_CRON_TRIGGERS: QrtzCronTriggers = QrtzCronTriggers.QRTZ_CRON_TRIGGERS

/**
 * The table <code>public.qrtz_fired_triggers</code>.
 */
val QRTZ_FIRED_TRIGGERS: QrtzFiredTriggers = QrtzFiredTriggers.QRTZ_FIRED_TRIGGERS

/**
 * The table <code>public.qrtz_job_details</code>.
 */
val QRTZ_JOB_DETAILS: QrtzJobDetails = QrtzJobDetails.QRTZ_JOB_DETAILS

/**
 * The table <code>public.qrtz_locks</code>.
 */
val QRTZ_LOCKS: QrtzLocks = QrtzLocks.QRTZ_LOCKS

/**
 * The table <code>public.qrtz_paused_trigger_grps</code>.
 */
val QRTZ_PAUSED_TRIGGER_GRPS: QrtzPausedTriggerGrps = QrtzPausedTriggerGrps.QRTZ_PAUSED_TRIGGER_GRPS

/**
 * The table <code>public.qrtz_scheduler_state</code>.
 */
val QRTZ_SCHEDULER_STATE: QrtzSchedulerState = QrtzSchedulerState.QRTZ_SCHEDULER_STATE

/**
 * The table <code>public.qrtz_simple_triggers</code>.
 */
val QRTZ_SIMPLE_TRIGGERS: QrtzSimpleTriggers = QrtzSimpleTriggers.QRTZ_SIMPLE_TRIGGERS

/**
 * The table <code>public.qrtz_simprop_triggers</code>.
 */
val QRTZ_SIMPROP_TRIGGERS: QrtzSimpropTriggers = QrtzSimpropTriggers.QRTZ_SIMPROP_TRIGGERS

/**
 * The table <code>public.qrtz_triggers</code>.
 */
val QRTZ_TRIGGERS: QrtzTriggers = QrtzTriggers.QRTZ_TRIGGERS

/**
 * The table <code>public.role</code>.
 */
val ROLE: Role = Role.ROLE

/**
 * The table <code>public.role_user_relation</code>.
 */
val ROLE_USER_RELATION: RoleUserRelation = RoleUserRelation.ROLE_USER_RELATION

/**
 * The table <code>public.user</code>.
 */
val USER: User = User.USER
